/**
 * Levanta auth + credential validation.
 *
 * Levanta's Creator API authenticates with a long-lived bearer token. The token
 * is generated by an account admin under Settings → API and handed to the
 * creator; it does not auto-rotate. That means:
 *   - No refresh flow is required for v0.1 — we treat the token as a static
 *     secret loaded from `LEVANTA_API_KEY`.
 *   - The auth-check endpoint is `GET /partners`, the cheapest authenticated
 *     Creator endpoint (it lists the brands the token has active partnerships
 *     with). A valid token returns 200; an invalid token returns a 401 with a
 *     JSON error body.
 *
 * Unlike Awin there is no second identifier to derive: the token is already
 * scoped to a single creator account, so no `derivedValues` flow is needed and
 * `LEVANTA_API_KEY` is the only credential.
 */

import { levantaRequest } from './client.js';
import { requireCredential } from '../../shared/config.js';
import { buildErrorEnvelope, NetworkError } from '../../shared/errors.js';
import { DEFAULT_RESILIENCE } from '../../shared/resilience.js';
import type {
  CredentialValidationResult,
  NetworkErrorEnvelope,
} from '../../shared/types.js';
import { createLogger } from '../../shared/logging.js';

const log = createLogger('levanta.auth');

export interface VerifyAuthOk {
  ok: true;
  identity?: string;
}

export interface VerifyAuthFail {
  ok: false;
  reason: string;
  envelope?: NetworkErrorEnvelope;
}

/**
 * The minimal shape we read off Levanta's `GET /partners` response.
 *
 * Levanta returns the active brand partnerships. The field names below are not
 * machine-verifiable from the public docs (the reference host gates automated
 * fetches), so we read several plausible keys and never over-specify. The
 * verbatim payload is preserved on `rawNetworkData` by the transformer.
 */
interface LevantaPartnerRaw {
  id?: string | number;
  brandId?: string | number;
  name?: string;
  brandName?: string;
}

interface LevantaPartnersEnvelope {
  partners?: LevantaPartnerRaw[];
  data?: LevantaPartnerRaw[];
}

/**
 * Verify the Levanta token by calling `GET /partners`.
 *
 * Why this endpoint:
 *   - It is the smallest authenticated Creator endpoint with a predictable
 *     200 / 401 response pattern.
 *   - It reveals the brand partnerships the token can act for, so the identity
 *     string is meaningful ("levanta (N active partnerships)").
 *
 * On success we return a short identity summarising the partnership count. The
 * token does not encode a separate creator id, so there is nothing to derive.
 */
export async function verifyAuth(): Promise<VerifyAuthOk | VerifyAuthFail> {
  let token: string;
  try {
    token = requireCredential('LEVANTA_API_KEY', {
      network: 'levanta',
      operation: 'verifyAuth',
      hint: 'Generate a token in the Levanta dashboard → Settings → API (requires Admin access).',
    });
  } catch (err) {
    if (err instanceof NetworkError) {
      return { ok: false, reason: err.envelope.message, envelope: err.envelope };
    }
    throw err;
  }

  try {
    const response = await levantaRequest<LevantaPartnersEnvelope | LevantaPartnerRaw[]>({
      operation: 'verifyAuth',
      path: '/v2/creator/partners',
      token,
      resilience: DEFAULT_RESILIENCE,
    });

    const partners = normalisePartnersResponse(response);
    const identity =
      partners.length > 0
        ? `levanta (${partners.length} active partnership${partners.length === 1 ? '' : 's'})`
        : 'levanta (authenticated; no active partnerships)';

    log.debug({ count: partners.length }, 'levanta verifyAuth succeeded');
    return { ok: true, identity };
  } catch (err) {
    if (err instanceof NetworkError) {
      return { ok: false, reason: err.envelope.message, envelope: err.envelope };
    }
    const envelope = buildErrorEnvelope({
      type: 'network_api_error',
      network: 'levanta',
      operation: 'verifyAuth',
      message: err instanceof Error ? err.message : String(err),
    });
    return { ok: false, reason: envelope.message, envelope };
  }
}

/**
 * Levanta's `/partners` response may be a bare array or wrapped in an envelope
 * (`partners` / `data`). Accept either; a future schema change becomes a
 * one-line addition here.
 */
export function normalisePartnersResponse(
  response: LevantaPartnersEnvelope | LevantaPartnerRaw[],
): LevantaPartnerRaw[] {
  if (Array.isArray(response)) return response;
  if (Array.isArray(response.partners)) return response.partners;
  if (Array.isArray(response.data)) return response.data;
  return [];
}

/**
 * Validate a single credential field at wizard-entry time.
 *
 * LEVANTA_API_KEY:
 *   Writes the candidate token into process.env, runs verifyAuth(), then
 *   restores the previous value. Returns ok on success with the discovered
 *   partnership summary in `message`.
 */
export async function validateCredential(
  field: string,
  value: string,
): Promise<CredentialValidationResult> {
  if (field === 'LEVANTA_API_KEY') {
    const previous = process.env['LEVANTA_API_KEY'];
    process.env['LEVANTA_API_KEY'] = value;
    try {
      const result = await verifyAuth();
      if (result.ok) {
        return { ok: true, message: result.identity ?? 'token verified' };
      }
      return {
        ok: false,
        message: result.reason,
        hint:
          'Check the token in the Levanta dashboard → Settings → API. The token may be revoked, ' +
          'lack Admin access, or have been copied with leading/trailing whitespace.',
      };
    } finally {
      // Restore the previous value so a failed validation does not poison
      // subsequent operations in the same process (test isolation).
      if (previous === undefined) {
        delete process.env['LEVANTA_API_KEY'];
      } else {
        process.env['LEVANTA_API_KEY'] = previous;
      }
    }
  }

  return {
    ok: false,
    message: `Unknown credential field "${field}" for Levanta.`,
    hint: 'Levanta expects LEVANTA_API_KEY (required).',
  };
}
