/**
 * Levanta HTTP client — the ONLY path Levanta adapter methods use for network I/O.
 *
 * Levanta's Creator API authenticates with a bearer token
 * (`Authorization: Bearer <token>`), generated by an account admin under
 * Settings → API. All credential reading and header construction is centralised
 * here so the adapter stays readable and the resilience layer applies uniformly
 * to every outgoing call.
 *
 * Hard rules (mirrored from Awin client.ts — read that file for the full
 * rationale):
 *   1. Do NOT call `fetch` from `adapter.ts` or anywhere else in this folder.
 *   2. Do NOT add a second client that skips `withResilience`.
 *   3. On a non-2xx response, throw `HttpStatusError` so the resilience layer
 *      can apply its retry policy uniformly.
 *   4. Preserve the raw response body verbatim on failure.
 *
 * --- API map (verify against https://api-docs.levanta.io/v2/creator) ----------
 *
 *   GET /partners   → active brand partnerships (brand id + name).
 *   GET /products   → product catalogue, filterable by ASIN / brandId / commission.
 *   GET /reports    → daily performance per link/source within a date range
 *                     (clicks, add-to-carts, conversions, sales, commissions).
 *   GET /links      → tracking links by ASIN/source pair (create + manage).
 *
 * The endpoint reference host (`api-docs.levanta.io`) gates automated fetches,
 * so field names, pagination, and date params below are modelled defensively:
 * every transformer treats every field as possibly absent and preserves the
 * verbatim payload under `rawNetworkData`.
 */

import {
  HttpStatusError,
  withResilience,
  type WithResilienceContext,
} from '../../shared/resilience.js';
import { buildErrorEnvelope, NetworkError } from '../../shared/errors.js';
import type { ResilienceConfig } from '../../shared/types.js';
import { createLogger } from '../../shared/logging.js';

const log = createLogger('levanta.client');

/**
 * The Levanta Creator API root. Centralised so a test harness or staging
 * environment can override it without touching adapter code. Hard-coded for
 * v0.1. The endpoint reference at `api-docs.levanta.io` documents the paths
 * under a `/v2/creator` prefix; that prefix is applied per-request by the
 * adapter rather than baked into the base so the seam stays visible.
 */
export const LEVANTA_BASE_URL = 'https://api.levanta.io';

export interface LevantaRequestInput {
  /** The canonical operation name. Used as the breaker key and in error envelopes. */
  operation: string;
  /** Path beginning with `/` — joined to `LEVANTA_BASE_URL`. */
  path: string;
  /** Bearer token. Passed in from auth helpers so credential reads happen once per op. */
  token: string;
  method?: 'GET' | 'POST' | 'PUT' | 'DELETE';
  /** Query string parameters. Values with `undefined` are skipped. */
  query?: Record<string, string | number | undefined>;
  /** Body for POST/PUT requests; serialised as JSON. */
  body?: unknown;
  /** Resilience knobs for this specific call. Required so each op picks its own profile. */
  resilience: ResilienceConfig;
  /** Optional `AbortSignal` for cooperative cancellation in tests. */
  signal?: AbortSignal;
}

/**
 * Issue a single Levanta API request under the resilience policy.
 *
 * Why the response is typed as `T` with no runtime validation: the Creator
 * API's response shapes are not machine-readable from the public docs, so
 * over-specifying a Zod schema here would force the client into the business
 * of "is this a valid Levanta response?", which belongs in the adapter's
 * transformer. The cost is that adapter transformers MUST tolerate missing
 * keys defensively.
 */
export async function levantaRequest<T>(input: LevantaRequestInput): Promise<T> {
  const ctx: WithResilienceContext = { network: 'levanta', operation: input.operation };

  return withResilience(
    ctx,
    async () => {
      const url = buildUrl(input.path, input.query);
      const init: RequestInit = {
        method: input.method ?? 'GET',
        headers: buildHeaders(input.token, input.body !== undefined),
      };
      if (input.body !== undefined) {
        init.body = JSON.stringify(input.body);
      }
      if (input.signal) {
        init.signal = input.signal;
      }

      log.debug({ url, method: init.method, operation: input.operation }, 'levanta request');

      const res = await fetch(url, init);

      // Read the body once. We need it both for success (decode JSON) and for
      // failure (surface the raw text on the envelope). Preserving the raw text
      // means the user sees the actual content even when a CDN fronts an error.
      const rawBody = await res.text();

      if (!res.ok) {
        throw new HttpStatusError(
          res.status,
          rawBody,
          `Levanta ${input.operation} ${init.method ?? 'GET'} ${input.path} → HTTP ${res.status}`,
        );
      }

      if (rawBody.trim() === '') {
        return {} as T;
      }

      try {
        return JSON.parse(rawBody) as T;
      } catch (err) {
        throw new NetworkError(
          buildErrorEnvelope({
            type: 'network_api_error',
            network: 'levanta',
            operation: input.operation,
            httpStatus: res.status,
            networkErrorBody: rawBody,
            message: `Levanta ${input.operation} returned HTTP ${res.status} with non-JSON body (parse error: ${(err as Error).message})`,
          }),
        );
      }
    },
    input.resilience,
  );
}

/**
 * Build the Levanta auth headers.
 *
 * Levanta uses the standard `Authorization: Bearer <token>` convention. The
 * `Accept` header is set to `application/json` because every Creator API
 * endpoint returns JSON.
 */
function buildHeaders(token: string, hasBody: boolean): Record<string, string> {
  const headers: Record<string, string> = {
    Authorization: `Bearer ${token}`,
    Accept: 'application/json',
  };
  if (hasBody) {
    headers['Content-Type'] = 'application/json';
  }
  return headers;
}

/**
 * Compose the full URL with query string, using `URL` + `URLSearchParams`.
 */
function buildUrl(pathname: string, query?: Record<string, string | number | undefined>): string {
  const url = new URL(pathname.startsWith('/') ? pathname : `/${pathname}`, LEVANTA_BASE_URL);
  if (query) {
    for (const [k, v] of Object.entries(query)) {
      if (v === undefined) continue;
      url.searchParams.set(k, String(v));
    }
  }
  return url.toString();
}

// Re-export so adapter code can throw HttpStatusError without importing from
// shared/resilience directly.
export { HttpStatusError };
