/**
 * Commission Factory adapter — publisher-side implementation.
 *
 * READ ME FIRST (agents adding other networks):
 *
 * This file follows the pattern of `src/networks/awin/adapter.ts` (the canonical
 * reference) and `src/networks/skimlinks/adapter.ts`. The load-bearing decisions
 * replicated here:
 *   - Never call `fetch` outside `client.ts`.
 *   - Every failure round-trips through a `NetworkErrorEnvelope`.
 *   - Raw payloads are preserved in `rawNetworkData` on every domain object.
 *   - Status enums are normalised with a documented mapping helper.
 *   - `ageDays` is computed per transaction.
 *   - UK English; "programme" not "program".
 *
 * --- Commission Factory API map -----------------------------------------------
 *
 * Base URL: https://api.commissionfactory.com/V1/
 *   Source: https://dev.commissionfactory.com/V1/
 *           https://dev.commissionfactory.com/V1/CallingApiFunctions/
 *
 * Auth: a single API key passed as the `apiKey` query parameter (no bearer header,
 * no OAuth). Generated by the account holder under their user profile.
 *   Source: https://dev.commissionfactory.com/V1/GeneratingApiKeys/
 *
 * GET /Affiliate/Merchants
 *   → array of Merchant: { Id, Name, AvatarUrl, CommissionType, CommissionRate,
 *       Status (e.g. "Joined"), TrackingUrl, TargetUrl, ... }
 *   Source: https://dev.commissionfactory.com/V1/Affiliate/Functions/GetMerchants/
 *           https://dev.commissionfactory.com/V1/Affiliate/Types/Merchant/
 *
 * GET /Affiliate/Merchants/{id}
 *   → single Merchant (used by getProgramme and generateTrackingLink)
 *   Source: https://dev.commissionfactory.com/V1/Affiliate/Functions/GetMerchantsId/
 *
 * GET /Affiliate/Transactions
 *   ?fromDate=YYYY-MM-DD&toDate=YYYY-MM-DD
 *   [&merchantId=N][&status2=Pending|Confirmed|Declined|Void|Paid]
 *   → array of Transaction: { Id, DateCreated, DateModified, MerchantId,
 *       MerchantName, OrderDate, OrderId, ReportedCurrencyCode, ReportedSaleValue,
 *       SaleValue, Commission, Status, Status2, CouponCode, UniqueId, VoidReason, ... }
 *   Date range is inclusive; fromDate/toDate are date-only (time ignored).
 *   Source: https://dev.commissionfactory.com/V1/Affiliate/Functions/GetTransactions/
 *           https://dev.commissionfactory.com/V1/Affiliate/Types/Transaction/
 *           https://dev.commissionfactory.com/V1/Affiliate/Types/TransactionStatus2/
 *   BLOCKED(verify): pagination parameters for this endpoint are not documented
 *   publicly (no page/pageSize/skip/take found). The adapter passes the full
 *   window in a single call; a live account test is required to confirm there is
 *   no server-side cap on the returned set.
 *
 * Tracking links: each joined Merchant carries a TrackingUrl such as
 *   https://t.cfjump.com/0/t/{id}. A deep link is formed by the banner/deep-link
 *   form https://t.cfjump.com/0/b/{id}?Url={encodedDestination}.
 *   Source: https://dev.commissionfactory.com/V1/Affiliate/Types/TrackingUrl/
 *           https://help.commissionfactory.com/creating-text-of-deep-links
 *   BLOCKED(verify): the exact path segment for deep links (.../b/{id}) vs text
 *   links (.../t/{id}) and the query key (`Url`) are taken from the docs example
 *   and the help-centre article; confirm against a live account before promoting.
 *
 * Clicks: the public Affiliate API does not expose click-level data. listClicks
 * throws NotImplementedError.
 *
 * --- Cardinal rules (non-negotiable) ------------------------------------------
 *
 *   1. Never call `fetch` outside `client.ts`. Use `commissionFactoryRequest`.
 *   2. Every failure round-trips through a `NetworkErrorEnvelope`. Never swallow.
 *   3. Preserve raw payloads in `rawNetworkData` on every domain object.
 *   4. Normalise status enums. See `mapTransactionStatus` and `mapProgrammeStatus`.
 *      Prefer `unknown`/`other` over a wrong guess.
 *   5. Compute `ageDays` per transaction. See `computeAgeDays`.
 *   6. Read credentials via `requireCredential` from shared/config — NEVER process.env
 *      (except in tests).
 *   7. UK English. "programme", not "program".
 */

import { commissionFactoryRequest } from './client.js';
import { verifyAuth as authVerify, validateCredential as authValidate, requireApiKey } from './auth.js';
import { setupSteps } from './setup.js';
import { buildErrorEnvelope, NetworkError } from '../../shared/errors.js';
import { DEFAULT_RESILIENCE } from '../../shared/resilience.js';
import { registerAdapter } from '../../shared/registry.js';
import { createLogger } from '../../shared/logging.js';
import {
  NotImplementedError,
  type Click,
  type ClickQuery,
  type CommissionRateStructured,
  type CredentialValidationResult,
  type EarningsByProgramme,
  type EarningsByStatus,
  type EarningsSummary,
  type NetworkAdapter,
  type NetworkCapabilities,
  type NetworkMeta,
  type OperationCapability,
  type Programme,
  type ProgrammeQuery,
  type ProgrammeStatus,
  type ResilienceConfig,
  type ResilienceConfigMap,
  type SetupStep,
  type TrackingLink,
  type Transaction,
  type TransactionQuery,
  type TransactionStatus,
} from '../../shared/types.js';

const log = createLogger('commission-factory.adapter');

const SLUG = 'commission-factory';
const NAME = 'Commission Factory';

const META: NetworkMeta = {
  slug: SLUG,
  name: NAME,
  baseUrl: 'https://api.commissionfactory.com/V1/',
  authModel: 'custom',
  docsUrl: 'https://dev.commissionfactory.com/V1/',
  adapterVersion: '0.1.0',
  lastVerified: '2026-06-04',
  claimStatus: 'experimental',
  knownLimitations: [
    'Adapter built from public API documentation; not yet verified against a live account.',
    'Commission Factory authenticates with a single API key passed as the `apiKey` query parameter (not a bearer header); authModel is therefore `custom`.',
    'listClicks is not exposed via the public Affiliate API; the operation throws NotImplementedError.',
    'generateTrackingLink reads the joined merchant TrackingUrl (https://t.cfjump.com/0/b/{id}) via GET /Affiliate/Merchants/{id} and appends ?Url={encoded}; it requires the merchant to be joined and reachable, and throws a network error for a merchant the affiliate has not joined.',
    'Affiliate API pagination for GET /Affiliate/Transactions is not documented publicly; the adapter passes the full date window in a single call. A live account test is required to confirm there is no server-side cap.',
    'The deprecated TransactionStatus enumeration is read only as a fallback; the adapter prefers Status2 (Pending, Confirmed, Declined, Void, Paid).',
  ],
  supportsBrandOps: false,
  setupTimeEstimateMinutes: 10,
  setupRequiresApproval: false,
  side: 'publisher',
  credentialScope: 'single-brand',
};

// ---------------------------------------------------------------------------
// Resilience profile
// ---------------------------------------------------------------------------

const TRANSACTIONS_RESILIENCE: ResilienceConfig = {
  ...DEFAULT_RESILIENCE,
  timeoutMs: 60_000,
  retries: 3,
};

const RESILIENCE: ResilienceConfigMap = {
  default: DEFAULT_RESILIENCE,
  listTransactions: TRANSACTIONS_RESILIENCE,
  getEarningsSummary: TRANSACTIONS_RESILIENCE,
};

// ---------------------------------------------------------------------------
// Commission Factory raw response shapes
// ---------------------------------------------------------------------------
//
// Why deliberately minimal: Commission Factory documents field names but the set
// can vary across functions and account types. Treating every field as possibly
// absent and preserving the original under `rawNetworkData` keeps the adapter
// robust to upstream drift.

interface CommissionFactoryTransactionRaw {
  Id?: string | number;
  DateCreated?: string; // ISO 8601 — when CF recorded the transaction
  DateModified?: string; // ISO 8601
  OrderDate?: string; // ISO 8601 — when the order was placed (conversion)
  OrderId?: string;
  MerchantId?: string | number;
  MerchantName?: string;
  ReportedCurrencyCode?: string; // e.g. "AUD"
  ReportedSaleValue?: number | string;
  SaleValue?: number | string; // gross sale value
  Commission?: number | string; // commission to the affiliate
  Status?: string; // deprecated TransactionStatus enum (fallback)
  Status2?: string; // TransactionStatus2: Pending | Confirmed | Declined | Void | Paid
  CouponCode?: string;
  UniqueId?: string;
  VoidReason?: string; // set when the transaction is voided/declined
}

interface CommissionFactoryMerchantRaw {
  Id?: string | number;
  Name?: string;
  AvatarUrl?: string;
  CommissionType?: string; // e.g. "Percentage", "Fixed", "Percent per Sale"
  CommissionRate?: number | string;
  Status?: string; // MerchantStatus: Joined | Pending | Declined | Suspended | ...
  TrackingUrl?: string; // e.g. https://t.cfjump.com/0/t/{id}
  TargetUrl?: string; // the merchant's destination site
  Currency?: string;
  CurrencyCode?: string;
}

// ---------------------------------------------------------------------------
// Status mapping helpers
// ---------------------------------------------------------------------------

/**
 * Map a Commission Factory transaction status to the canonical TransactionStatus.
 *
 * Commission Factory's current enum is `TransactionStatus2`; the older
 * `TransactionStatus` is deprecated. We read Status2 first and fall back to Status.
 *
 *   Pending             → 'pending'   (awaiting validation)
 *   Confirmed           → 'approved'  (validated, not yet paid out)
 *   Paid                → 'paid'      (settled / included in an invoice)
 *   Declined / Void     → 'reversed'  (the sale did not pay out)
 *   anything else       → 'other'
 *
 * Why 'Declined'/'Void' → 'reversed': from the publisher's perspective both mean
 * the sale did not pay out — semantically a reversal, matching what other
 * networks call this state. The verbatim status is preserved in `rawNetworkData`.
 */
function mapTransactionStatus(raw: CommissionFactoryTransactionRaw): TransactionStatus {
  const s = (raw.Status2 ?? raw.Status ?? '').toLowerCase().trim();
  if (s === 'pending') return 'pending';
  if (s === 'confirmed' || s === 'approved' || s === 'accepted') return 'approved';
  if (s === 'paid') return 'paid';
  if (s === 'declined' || s === 'void' || s === 'voided' || s === 'reversed' || s === 'rejected') {
    return 'reversed';
  }
  return 'other';
}

/**
 * Map a Commission Factory merchant status to the canonical ProgrammeStatus.
 *
 *   Joined / Active       → 'joined'
 *   Pending               → 'pending'
 *   Declined / Rejected   → 'declined'
 *   Available / NotJoined → 'available'
 *   Suspended / Paused    → 'suspended'
 *   anything else         → 'unknown'
 */
function mapProgrammeStatus(raw: { Status?: string }): ProgrammeStatus {
  const s = (raw.Status ?? '').toLowerCase().trim();
  if (s === 'joined' || s === 'active' || s === 'approved') return 'joined';
  if (s === 'pending') return 'pending';
  if (s === 'declined' || s === 'rejected') return 'declined';
  if (s === 'available' || s === 'notjoined' || s === 'not joined') return 'available';
  if (s === 'suspended' || s === 'paused') return 'suspended';
  return 'unknown';
}

/**
 * Map a Commission Factory CommissionType/CommissionRate pair to the structured
 * commission rate shape. We pick the closest of the canonical types and preserve
 * the verbatim source in `rawNetworkData` on the Programme.
 */
function mapCommissionRate(raw: CommissionFactoryMerchantRaw): CommissionRateStructured | undefined {
  if (raw.CommissionType === undefined && raw.CommissionRate === undefined) return undefined;
  const t = (raw.CommissionType ?? '').toLowerCase();
  const value = toAmount(raw.CommissionRate);
  let type: CommissionRateStructured['type'] = 'unknown';
  if (t.includes('percent')) type = 'percent';
  else if (t.includes('fixed') || t.includes('flat') || t.includes('amount')) type = 'flat';
  const out: CommissionRateStructured = { type };
  if (raw.CommissionRate !== undefined) out.value = value;
  if (raw.CommissionType) out.description = raw.CommissionType;
  return out;
}

// ---------------------------------------------------------------------------
// Domain object transformers
// ---------------------------------------------------------------------------

/**
 * Compute the age (in days) of a Commission Factory transaction at the moment
 * the adapter responded. The unpaid-age affordance depends on this.
 *
 * Anchor priority: OrderDate (the conversion date) is the most meaningful and
 * earliest anchor; fall back to DateCreated (when CF recorded the transaction).
 */
function computeAgeDays(raw: CommissionFactoryTransactionRaw, now: Date = new Date()): number {
  const anchor = raw.OrderDate ?? raw.DateCreated;
  if (!anchor) return 0;
  const t = Date.parse(anchor);
  if (Number.isNaN(t)) return 0;
  const ms = now.getTime() - t;
  return Math.max(0, Math.floor(ms / (1000 * 60 * 60 * 24)));
}

function nullableIso(d?: string | null): string | undefined {
  if (!d) return undefined;
  const ts = Date.parse(d);
  return Number.isNaN(ts) ? undefined : new Date(ts).toISOString();
}

function toAmount(v: number | string | undefined): number {
  if (v === undefined || v === null) return 0;
  const n = typeof v === 'number' ? v : parseFloat(String(v));
  return Number.isNaN(n) ? 0 : n;
}

function toTransaction(
  raw: CommissionFactoryTransactionRaw,
  now: Date = new Date(),
): Transaction {
  const status = mapTransactionStatus(raw);
  const commission = toAmount(raw.Commission);
  const sale = toAmount(raw.SaleValue ?? raw.ReportedSaleValue);
  // Currency is read per transaction — Commission Factory is APAC-centric (often
  // AUD) but we never hardcode; default only when the field is genuinely absent.
  const currency = (raw.ReportedCurrencyCode ?? 'AUD').toUpperCase();

  const orderDate = nullableIso(raw.OrderDate) ?? nullableIso(raw.DateCreated) ?? new Date(0).toISOString();
  const createdDate = nullableIso(raw.DateCreated);
  // Commission Factory does not expose an approval timestamp distinct from
  // DateModified; we surface DateModified as the approved date only when the
  // transaction is approved/paid, otherwise leave it undefined.
  const approvedDate =
    status === 'approved' || status === 'paid' ? nullableIso(raw.DateModified) : undefined;
  const paidDate = status === 'paid' ? nullableIso(raw.DateModified) : undefined;

  return {
    id: String(raw.Id ?? ''),
    network: SLUG,
    programmeId: String(raw.MerchantId ?? ''),
    programmeName: raw.MerchantName ?? `Commission Factory merchant ${raw.MerchantId ?? ''}`,
    status,
    amount: sale,
    currency,
    commission,
    dateClicked: createdDate,
    dateConverted: orderDate,
    dateApproved: approvedDate,
    datePaid: paidDate,
    ageDays: computeAgeDays(raw, now),
    reversalReason: status === 'reversed' ? raw.VoidReason ?? undefined : undefined,
    rawNetworkData: raw,
  };
}

function toProgramme(raw: CommissionFactoryMerchantRaw): Programme {
  const currency = (raw.CurrencyCode ?? raw.Currency)?.toUpperCase();
  const rate = mapCommissionRate(raw);
  const programme: Programme = {
    id: String(raw.Id ?? ''),
    name: raw.Name ?? `Commission Factory merchant ${raw.Id ?? ''}`,
    network: SLUG,
    status: mapProgrammeStatus(raw),
    rawNetworkData: raw,
  };
  if (currency) programme.currency = currency;
  if (rate) programme.commissionRate = rate;
  if (raw.TargetUrl) programme.advertiserUrl = raw.TargetUrl;
  return programme;
}

// ---------------------------------------------------------------------------
// The adapter
// ---------------------------------------------------------------------------

export class CommissionFactoryAdapter implements NetworkAdapter {
  readonly slug = SLUG;
  readonly name = NAME;
  readonly meta = META;
  readonly resilienceConfig = RESILIENCE;

  // -------------------------------------------------------------------------
  // listProgrammes
  // -------------------------------------------------------------------------

  /**
   * List the merchants (programmes) reachable by the affiliate's API key.
   *
   *   GET /Affiliate/Merchants
   *   Source: https://dev.commissionfactory.com/V1/Affiliate/Functions/GetMerchants/
   *
   * Filtering by status / search / category is applied client-side after the
   * normalising transform, so the canonical ProgrammeStatus is what callers match
   * against (not the upstream string).
   */
  async listProgrammes(query?: ProgrammeQuery): Promise<Programme[]> {
    const apiKey = requireApiKey('listProgrammes');

    const response = await commissionFactoryRequest<unknown>({
      operation: 'listProgrammes',
      path: '/Affiliate/Merchants',
      apiKey,
      resilience: RESILIENCE.default,
    });

    const rawMerchants = asArray<CommissionFactoryMerchantRaw>(response);
    let programmes = rawMerchants.map((m) => toProgramme(m));

    const statusFilter = toProgrammeStatusList(query?.status);
    if (statusFilter && statusFilter.length > 0) {
      const set = new Set(statusFilter);
      programmes = programmes.filter((p) => set.has(p.status));
    }

    if (query?.search) {
      const needle = query.search.toLowerCase();
      programmes = programmes.filter((p) => p.name.toLowerCase().includes(needle));
    }

    if (typeof query?.limit === 'number') {
      programmes = programmes.slice(0, query.limit);
    }

    log.debug({ count: programmes.length }, 'listProgrammes complete');
    return programmes;
  }

  // -------------------------------------------------------------------------
  // getProgramme
  // -------------------------------------------------------------------------

  /**
   * Fetch a single merchant (programme) by id.
   *
   *   GET /Affiliate/Merchants/{id}
   *   Source: https://dev.commissionfactory.com/V1/Affiliate/Functions/GetMerchantsId/
   */
  async getProgramme(programmeId: string): Promise<Programme> {
    if (!programmeId) {
      throw new NetworkError(
        buildErrorEnvelope({
          type: 'config_error',
          network: SLUG,
          operation: 'getProgramme',
          message: 'programmeId is required.',
          hint: 'Pass the Commission Factory merchant Id.',
        }),
      );
    }
    const apiKey = requireApiKey('getProgramme');
    const response = await commissionFactoryRequest<CommissionFactoryMerchantRaw>({
      operation: 'getProgramme',
      path: `/Affiliate/Merchants/${encodeURIComponent(programmeId)}`,
      apiKey,
      resilience: RESILIENCE.default,
    });
    return toProgramme(response ?? {});
  }

  // -------------------------------------------------------------------------
  // listTransactions
  // -------------------------------------------------------------------------

  /**
   * List Commission Factory transactions across a date window with optional
   * status / age / merchant filters.
   *
   *   GET /Affiliate/Transactions
   *     ?fromDate=YYYY-MM-DD&toDate=YYYY-MM-DD
   *     [&merchantId={merchantId}][&status2={Status2}]
   *
   * The date range is inclusive and date-only (time components are ignored by the
   * server). We default to a 30-day window when none is supplied.
   *
   * BLOCKED(verify): no pagination parameters are documented for this endpoint;
   * we pass the full window in one call. A live account test is required to
   * confirm there is no server-side cap on the result set.
   *
   * Status filtering: a single requested status is mapped to the upstream Status2
   * value as a server-side hint. We ALWAYS re-filter client-side on the canonical
   * status after transformation, because the server filter speaks upstream enum
   * names (e.g. "Declined") while callers query canonical names (e.g. "reversed"),
   * and "other" has no upstream equivalent.
   */
  async listTransactions(query?: TransactionQuery): Promise<Transaction[]> {
    const apiKey = requireApiKey('listTransactions');
    const now = new Date();

    const to = query?.to ? new Date(query.to) : now;
    const from = query?.from
      ? new Date(query.from)
      : new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000);

    const params: Record<string, string | number | undefined> = {
      fromDate: from.toISOString().slice(0, 10),
      toDate: to.toISOString().slice(0, 10),
    };

    const statusFilter = toTransactionStatusList(query?.status);
    const singleStatusUpstream = mapCanonicalToCfStatus(statusFilter);
    if (singleStatusUpstream) {
      params['status2'] = singleStatusUpstream;
    }

    if (query?.programmeId) {
      params['merchantId'] = query.programmeId;
    }

    const response = await commissionFactoryRequest<unknown>({
      operation: 'listTransactions',
      path: '/Affiliate/Transactions',
      apiKey,
      query: params,
      resilience: RESILIENCE.listTransactions ?? RESILIENCE.default,
    });

    const rawTransactions = asArray<CommissionFactoryTransactionRaw>(response);
    let transactions = rawTransactions.map((r) => toTransaction(r, now));

    // Client-side canonical status filter — always applied when a status filter
    // was requested (see method comment for why we re-filter even with a server hint).
    if (statusFilter && statusFilter.length > 0) {
      const set = new Set(statusFilter);
      transactions = transactions.filter((t) => set.has(t.status));
    }

    const minAge = query?.minAgeDays;
    if (typeof minAge === 'number') {
      transactions = transactions.filter((t) => t.ageDays >= minAge);
    }
    const maxAge = query?.maxAgeDays;
    if (typeof maxAge === 'number') {
      transactions = transactions.filter((t) => t.ageDays <= maxAge);
    }

    if (typeof query?.limit === 'number') {
      transactions = transactions.slice(0, query.limit);
    }

    log.debug({ count: transactions.length }, 'listTransactions complete');
    return transactions;
  }

  // -------------------------------------------------------------------------
  // getEarningsSummary
  // -------------------------------------------------------------------------

  /**
   * Aggregate transactions into an earnings summary.
   *
   * Derived from `listTransactions` so there is one source of truth, and so the
   * per-transaction `ageDays` is available to compute `oldestUnpaidAgeDays`.
   *
   * Do NOT pass `query.limit` through — a limited summary undercounts (principle 4.1).
   */
  async getEarningsSummary(query?: TransactionQuery): Promise<EarningsSummary> {
    const now = new Date();
    const from = query?.from ?? new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000).toISOString();
    const to = query?.to ?? now.toISOString();

    const txns = await this.listTransactions({
      ...query,
      from,
      to,
      limit: undefined,
    });

    const byProgrammeMap = new Map<string, EarningsByProgramme>();
    const byStatus: EarningsByStatus = {
      pending: 0,
      approved: 0,
      reversed: 0,
      paid: 0,
      other: 0,
      currency: 'AUD',
    };

    let totalEarnings = 0;
    let firstCurrency: string | undefined;
    let oldestUnpaidAgeDays: number | undefined;

    for (const t of txns) {
      if (!firstCurrency) firstCurrency = t.currency;

      byStatus[t.status] = (byStatus[t.status] ?? 0) + t.commission;
      totalEarnings += t.commission;

      const key = t.programmeId || '__unknown';
      const existing = byProgrammeMap.get(key);
      if (existing) {
        existing.total += t.commission;
        existing.transactionCount += 1;
      } else {
        byProgrammeMap.set(key, {
          programmeId: key,
          programmeName: t.programmeName || `Commission Factory merchant ${key}`,
          total: t.commission,
          currency: t.currency,
          transactionCount: 1,
        });
      }

      if (t.status === 'pending' || t.status === 'approved') {
        if (oldestUnpaidAgeDays === undefined || t.ageDays > oldestUnpaidAgeDays) {
          oldestUnpaidAgeDays = t.ageDays;
        }
      }
    }

    if (firstCurrency) byStatus.currency = firstCurrency;

    return {
      network: SLUG,
      totalEarnings,
      currency: firstCurrency ?? 'AUD',
      byProgramme: [...byProgrammeMap.values()],
      byStatus,
      oldestUnpaidAgeDays,
      periodFrom: from,
      periodTo: to,
    };
  }

  // -------------------------------------------------------------------------
  // listClicks
  // -------------------------------------------------------------------------

  /**
   * Commission Factory does not expose click-level data via the public Affiliate API.
   *
   * We throw NotImplementedError rather than returning an empty array — the
   * difference between "no clicks in the period" and "clicks not exposed by the API"
   * is principle 4.1.
   */
  async listClicks(_query?: ClickQuery): Promise<Click[]> {
    throw new NotImplementedError(
      'Commission Factory does not expose click-level data via the public Affiliate API.',
    );
  }

  // -------------------------------------------------------------------------
  // generateTrackingLink
  // -------------------------------------------------------------------------

  /**
   * Build a Commission Factory deep link for a destination URL on a joined merchant.
   *
   * Commission Factory does not let an affiliate mint a deep link from a
   * destination URL alone: the tracking host segment is merchant-specific. Each
   * merchant exposes a TrackingUrl such as `https://t.cfjump.com/0/t/{id}`; the
   * deep-link form is `https://t.cfjump.com/0/b/{id}?Url={encodedDestination}`.
   *
   * So we fetch the merchant (GET /Affiliate/Merchants/{id}), read its TrackingUrl,
   * derive the `/b/{id}` deep-link base, and append the encoded destination.
   *
   * Source: https://dev.commissionfactory.com/V1/Affiliate/Types/TrackingUrl/
   *         https://help.commissionfactory.com/creating-text-of-deep-links
   * BLOCKED(verify): the `/t/` → `/b/` segment swap and the `Url` query key are
   * taken from the docs example and help-centre article; confirm against a live
   * account before promoting the claim status.
   */
  async generateTrackingLink(input: {
    programmeId: string;
    destinationUrl: string;
  }): Promise<TrackingLink> {
    if (!input.destinationUrl) {
      throw new NetworkError(
        buildErrorEnvelope({
          type: 'config_error',
          network: SLUG,
          operation: 'generateTrackingLink',
          message: 'destinationUrl is required.',
          hint: 'Pass the full URL of the merchant page you want to link to.',
        }),
      );
    }
    if (!input.programmeId) {
      throw new NetworkError(
        buildErrorEnvelope({
          type: 'config_error',
          network: SLUG,
          operation: 'generateTrackingLink',
          message: 'programmeId is required.',
          hint: 'Commission Factory deep links are merchant-specific; pass the merchant Id you are linking to.',
        }),
      );
    }

    const apiKey = requireApiKey('generateTrackingLink');

    const merchant = await commissionFactoryRequest<CommissionFactoryMerchantRaw>({
      operation: 'generateTrackingLink',
      path: `/Affiliate/Merchants/${encodeURIComponent(input.programmeId)}`,
      apiKey,
      resilience: RESILIENCE.default,
    });

    const trackingUrl = merchant?.TrackingUrl;
    if (!trackingUrl) {
      throw new NetworkError(
        buildErrorEnvelope({
          type: 'network_api_error',
          network: SLUG,
          operation: 'generateTrackingLink',
          message: `Commission Factory merchant ${input.programmeId} returned no TrackingUrl; the affiliate may not have joined this programme.`,
          hint: 'Confirm the programme is joined and approved in the Commission Factory dashboard.',
        }),
      );
    }

    const deepLink = buildDeepLink(trackingUrl, input.destinationUrl);

    return {
      network: SLUG,
      destinationUrl: input.destinationUrl,
      trackingUrl: deepLink,
      programmeId: input.programmeId,
      createdAt: new Date().toISOString(),
      rawNetworkData: {
        merchantTrackingUrl: trackingUrl,
        deepLink,
        note: 'Deep link derived from the merchant TrackingUrl (.../t/{id} → .../b/{id}) with ?Url={encoded}.',
      },
    };
  }

  // -------------------------------------------------------------------------
  // verifyAuth
  // -------------------------------------------------------------------------

  /**
   * Verify credentials by making a cheap authorised call.
   *
   * On success: { ok: true, identity: '...' } (a redacted key fingerprint).
   * On failure: { ok: false, reason: '...' }. Never throws — verifyAuth is
   * called by error handlers.
   */
  async verifyAuth(): Promise<{ ok: true; identity?: string } | { ok: false; reason: string }> {
    const result = await authVerify();
    if (result.ok) {
      return result.identity ? { ok: true, identity: result.identity } : { ok: true };
    }
    return { ok: false, reason: result.reason };
  }

  // -------------------------------------------------------------------------
  // Admin operations
  // -------------------------------------------------------------------------

  async listPublishers(): Promise<never> {
    throw new NotImplementedError('Brand-side admin operations are scaffolded for v0.2.');
  }

  async listPublisherSectors(): Promise<never> {
    throw new NotImplementedError('Brand-side admin operations are scaffolded for v0.2.');
  }

  // -------------------------------------------------------------------------
  // validateCredential / setupSteps
  // -------------------------------------------------------------------------

  async validateCredential(field: string, value: string): Promise<CredentialValidationResult> {
    return authValidate(field, value);
  }

  setupSteps(): SetupStep[] {
    return setupSteps();
  }

  // -------------------------------------------------------------------------
  // capabilitiesCheck
  // -------------------------------------------------------------------------

  /**
   * Probe each operation with a minimal call.
   *
   * listClicks is known-unsupported and is recorded without probing.
   * generateTrackingLink needs a real merchant id to probe, so it is recorded as
   * supported-but-conditional without a live probe (avoids guessing an id).
   */
  async capabilitiesCheck(): Promise<NetworkCapabilities> {
    const operations: Record<string, OperationCapability> = {};

    const probe = async (
      name: string,
      fn: () => Promise<unknown>,
      note?: string,
    ): Promise<void> => {
      const start = Date.now();
      try {
        const result = await fn();
        const sampleSize = Array.isArray(result) ? result.length : 1;
        const cap: OperationCapability = {
          supported: true,
          latencyMs: Date.now() - start,
          sampleSize,
        };
        if (note !== undefined) cap.note = note;
        operations[name] = cap;
      } catch (err) {
        operations[name] = {
          supported: false,
          latencyMs: Date.now() - start,
          note: err instanceof Error ? err.message : String(err),
        };
      }
    };

    // Known-unsupported — record without probing.
    operations['listClicks'] = {
      supported: false,
      note: 'Commission Factory does not expose click-level data via the public Affiliate API.',
    };

    await probe('verifyAuth', () => this.verifyAuth());
    await probe('listProgrammes', () => this.listProgrammes({ limit: 1 }));
    await probe('listTransactions', () => this.listTransactions({ limit: 1 }));
    await probe('getEarningsSummary', () => this.getEarningsSummary({ limit: 1 }));

    // generateTrackingLink requires a concrete merchant id to exercise; record as
    // supported-but-conditional without guessing one.
    operations['generateTrackingLink'] = {
      supported: true,
      claimStatus: 'experimental',
      note: 'Requires a joined merchant Id; deep link derived from the merchant TrackingUrl. Not probed live (no merchant id available).',
    };

    return {
      network: SLUG,
      generatedAt: new Date().toISOString(),
      operations,
      knownLimitations: META.knownLimitations,
    };
  }
}

// ---------------------------------------------------------------------------
// Registration
// ---------------------------------------------------------------------------

export const commissionFactoryAdapter = new CommissionFactoryAdapter();
registerAdapter(commissionFactoryAdapter);

// ---------------------------------------------------------------------------
// Local helpers
// ---------------------------------------------------------------------------

/**
 * Commission Factory functions return either a bare JSON array or, in some
 * documented examples, an object wrapping the array (e.g. `{ Items: [...] }`).
 * Normalise both to a plain array so transformers do not have to guess.
 */
function asArray<T>(response: unknown): T[] {
  if (Array.isArray(response)) return response as T[];
  if (response && typeof response === 'object') {
    const obj = response as Record<string, unknown>;
    for (const key of ['Items', 'Data', 'Results', 'Transactions', 'Merchants']) {
      if (Array.isArray(obj[key])) return obj[key] as T[];
    }
  }
  return [];
}

/**
 * Build a Commission Factory deep link from a merchant TrackingUrl and a
 * destination URL.
 *
 * The merchant TrackingUrl is a text-link host like `https://t.cfjump.com/0/t/{id}`.
 * Deep links use the banner/deep-link segment `.../b/{id}` with the destination
 * passed as the `Url` query parameter.
 */
function buildDeepLink(trackingUrl: string, destinationUrl: string): string {
  // Swap the `/t/` text-link segment for the `/b/` deep-link segment where present.
  const deepBase = trackingUrl.includes('/t/')
    ? trackingUrl.replace('/t/', '/b/')
    : trackingUrl;
  const sep = deepBase.includes('?') ? '&' : '?';
  return `${deepBase}${sep}Url=${encodeURIComponent(destinationUrl)}`;
}

function toTransactionStatusList(
  v?: TransactionStatus | TransactionStatus[],
): TransactionStatus[] | undefined {
  if (v === undefined) return undefined;
  return Array.isArray(v) ? v : [v];
}

function toProgrammeStatusList(
  v?: ProgrammeStatus | ProgrammeStatus[],
): ProgrammeStatus[] | undefined {
  if (v === undefined) return undefined;
  return Array.isArray(v) ? v : [v];
}

/**
 * Map a set of canonical TransactionStatus values to a single Commission Factory
 * Status2 value. Returns undefined if the set requires client-side filtering
 * (multiple statuses, or a status with no single upstream equivalent).
 *
 * Canonical → CF Status2:
 *   pending   → 'Pending'
 *   approved  → 'Confirmed'
 *   paid      → 'Paid'
 *   reversed  → (no single value; CF splits into Declined + Void) → undefined
 *   other     → (no mapping) → undefined
 */
function mapCanonicalToCfStatus(statuses?: TransactionStatus[]): string | undefined {
  if (!statuses || statuses.length !== 1) return undefined;
  switch (statuses[0]) {
    case 'pending':
      return 'Pending';
    case 'approved':
      return 'Confirmed';
    case 'paid':
      return 'Paid';
    default:
      // 'reversed' maps to two upstream values (Declined, Void) so we cannot
      // express it as a single server filter; 'other' has no equivalent.
      return undefined;
  }
}

// ---------------------------------------------------------------------------
// Internal test helpers — exported so unit tests can exercise transformers
// directly without network calls.
// ---------------------------------------------------------------------------

export const _internals = {
  mapTransactionStatus,
  mapProgrammeStatus,
  mapCommissionRate,
  computeAgeDays,
  toTransaction,
  toProgramme,
  toAmount,
  asArray,
  buildDeepLink,
  mapCanonicalToCfStatus,
};

// Silence unused-import lint warning when noUnusedLocals is on.
void log;
