/**
 * Commission Factory auth + credential validation.
 *
 * Commission Factory authenticates with a single API key generated by the account
 * holder under their user profile (Account Settings → API). The key is passed as
 * the `apiKey` query parameter on every request — there is no OAuth flow and no
 * bearer header.
 *   Source: https://dev.commissionfactory.com/V1/GeneratingApiKeys/
 *           https://dev.commissionfactory.com/V1/CallingApiFunctions/
 *
 * --- verifyAuth ----------------------------------------------------------------
 *
 * Commission Factory does not document a dedicated `/me`-style identity endpoint
 * for affiliate accounts. We treat a successful, authorised call to
 * GET /Affiliate/Merchants as proof the key is valid (a bad key returns 401/403).
 * The API key is the account identity, so we surface a redacted fingerprint of it
 * rather than the raw key.
 *
 * verifyAuth never throws — it is called by error handlers, and a 401/403 must
 * resolve to { ok: false } rather than bubble up.
 */

import { commissionFactoryRequest } from './client.js';
import { requireCredential } from '../../shared/config.js';
import { buildErrorEnvelope, NetworkError } from '../../shared/errors.js';
import { DEFAULT_RESILIENCE } from '../../shared/resilience.js';
import type { CredentialValidationResult, NetworkErrorEnvelope } from '../../shared/types.js';
import { createLogger } from '../../shared/logging.js';

const log = createLogger('commission-factory.auth');

const SLUG = 'commission-factory';

/**
 * Read the configured API key, or throw a `config_error` envelope via
 * `requireCredential` if it is missing.
 */
export function requireApiKey(operation: string): string {
  return requireCredential('COMMISSION_FACTORY_API_KEY', {
    network: SLUG,
    operation,
    hint:
      'Set COMMISSION_FACTORY_API_KEY in ~/.affiliate-mcp/.env. ' +
      'Generate it in the Commission Factory dashboard under your user profile / Account Settings → API.',
  });
}

/**
 * Produce a short, non-reversible fingerprint of the API key for display in the
 * setup wizard. We never echo the raw key back to the user.
 */
function fingerprint(apiKey: string): string {
  const tail = apiKey.length >= 4 ? apiKey.slice(-4) : apiKey;
  return `commission-factory/key:****${tail}`;
}

export interface VerifyAuthOk {
  ok: true;
  identity?: string;
}

export interface VerifyAuthFail {
  ok: false;
  reason: string;
  envelope?: NetworkErrorEnvelope;
}

/**
 * Verify Commission Factory credentials by making a cheap authorised call.
 *
 * GET /Affiliate/Merchants is the lowest-cost call that exercises the API key:
 * an invalid key returns an auth error, a valid key returns the joined-merchant
 * list. We do not parse the body — the HTTP status is the signal.
 *
 * Never throws — returns { ok: false } on any failure.
 */
export async function verifyAuth(): Promise<VerifyAuthOk | VerifyAuthFail> {
  let apiKey: string;
  try {
    apiKey = requireApiKey('verifyAuth');
  } catch (err) {
    if (err instanceof NetworkError) {
      return { ok: false, reason: err.envelope.message, envelope: err.envelope };
    }
    throw err;
  }

  try {
    // A minimal authorised probe. The page size hint keeps the payload small
    // where the server honours it; an unsupported param is harmless.
    await commissionFactoryRequest<unknown>({
      operation: 'verifyAuth',
      path: '/Affiliate/Merchants',
      apiKey,
      resilience: DEFAULT_RESILIENCE,
    });

    const identity = fingerprint(apiKey);
    log.debug({ identity }, 'commission-factory verifyAuth succeeded');
    return { ok: true, identity };
  } catch (err) {
    if (err instanceof NetworkError) {
      return { ok: false, reason: err.envelope.message, envelope: err.envelope };
    }
    const envelope = buildErrorEnvelope({
      type: 'auth_error',
      network: SLUG,
      operation: 'verifyAuth',
      message: err instanceof Error ? err.message : String(err),
      hint: 'Check COMMISSION_FACTORY_API_KEY in your config.',
    });
    return { ok: false, reason: envelope.message, envelope };
  }
}

/**
 * Validate a single credential field at wizard-entry time.
 *
 * COMMISSION_FACTORY_API_KEY: format check (non-empty) followed by a live probe
 * against GET /Affiliate/Merchants with the entered value.
 */
export async function validateCredential(
  field: string,
  value: string,
): Promise<CredentialValidationResult> {
  if (field !== 'COMMISSION_FACTORY_API_KEY') {
    return {
      ok: false,
      message: `Unknown credential field "${field}" for Commission Factory.`,
      hint: 'Commission Factory expects COMMISSION_FACTORY_API_KEY.',
    };
  }

  if (!value || value.trim() === '') {
    return {
      ok: false,
      message: 'API key must not be empty.',
      hint: 'Generate it in the Commission Factory dashboard under your user profile / Account Settings → API.',
    };
  }

  // Temporarily inject the entered value so we can exercise the live probe.
  const prev = process.env['COMMISSION_FACTORY_API_KEY'];
  process.env['COMMISSION_FACTORY_API_KEY'] = value;
  try {
    const result = await verifyAuth();
    if (result.ok) {
      return {
        ok: true,
        message: result.identity ?? 'Credentials verified against the Commission Factory API.',
      };
    }
    return {
      ok: false,
      message: result.reason,
      hint: 'Check the API key was copied without leading or trailing spaces, and that it has not been revoked.',
    };
  } finally {
    if (prev === undefined) {
      delete process.env['COMMISSION_FACTORY_API_KEY'];
    } else {
      process.env['COMMISSION_FACTORY_API_KEY'] = prev;
    }
  }
}
