/**
 * Commission Factory HTTP client — the ONLY path adapter methods use for network I/O.
 *
 * Why this file exists separately from `adapter.ts`:
 *   - Adapter methods speak in normalised domain types; URL construction, the
 *     API-key injection, JSON parsing, and status handling live here.
 *   - The resilience layer (timeout, retry policy, circuit breaker — see
 *     `src/shared/resilience.ts`) is applied uniformly, exactly once per call.
 *
 * Hard rules:
 *   1. Do NOT call `fetch` from adapter.ts or anywhere else in this folder.
 *   2. Do NOT bypass `withResilience` for any call.
 *   3. On non-2xx, throw `HttpStatusError` so the resilience layer retries uniformly.
 *   4. Preserve the raw response body verbatim on failure (`networkErrorBody`).
 *
 * --- Commission Factory API surface (verified against public docs, 2026-06-04) ---
 *
 * Base URL: https://api.commissionfactory.com/V1/
 *   Source: https://dev.commissionfactory.com/V1/ (Getting Started),
 *           https://dev.commissionfactory.com/V1/CallingApiFunctions/
 *
 * Authentication: a single API key, generated by the account holder under their
 * user profile / account settings. The key is passed as the `apiKey` QUERY
 * PARAMETER on every request (NOT an Authorization/bearer header). Example from
 * the docs: GET https://api.commissionfactory.com/V1/Affiliate/Banners?apiKey=[apiKey]
 *   Source: https://dev.commissionfactory.com/V1/GeneratingApiKeys/
 *           https://dev.commissionfactory.com/V1/CallingApiFunctions/
 *
 * Affiliate (publisher-side) endpoints used:
 *   GET /V1/Affiliate/Merchants          → list joined merchants (programmes)
 *   GET /V1/Affiliate/Merchants/{id}     → single merchant (programme + TrackingUrl)
 *   GET /V1/Affiliate/Transactions       → ?fromDate=&toDate=&merchantId=&status2=
 *   Source: https://dev.commissionfactory.com/V1/Affiliate/Functions/
 *           https://dev.commissionfactory.com/V1/Affiliate/Functions/GetTransactions/
 *           https://dev.commissionfactory.com/V1/Affiliate/Functions/GetMerchants/
 *
 * Content negotiation: JSON by default; the adapter sends `Accept: application/json`.
 *   Source: https://dev.commissionfactory.com/V1/JsonOrXml/
 */

import {
  HttpStatusError,
  withResilience,
  type WithResilienceContext,
} from '../../shared/resilience.js';
import { buildErrorEnvelope, NetworkError } from '../../shared/errors.js';
import type { ResilienceConfig } from '../../shared/types.js';
import { createLogger } from '../../shared/logging.js';

const log = createLogger('commission-factory.client');

const SLUG = 'commission-factory';

/**
 * The Commission Factory production API base URL.
 * Source: https://dev.commissionfactory.com/V1/CallingApiFunctions/
 */
export const COMMISSION_FACTORY_BASE_URL = 'https://api.commissionfactory.com/V1/';

export interface CommissionFactoryRequestInput {
  /** The canonical operation name. Used as the breaker key and in error envelopes. */
  operation: string;
  /** Path beginning with `/` — joined to the base URL (relative to /V1/). */
  path: string;
  /** The API key, injected as the `apiKey` query parameter. */
  apiKey: string;
  method?: 'GET' | 'POST' | 'PUT' | 'DELETE';
  /** Query string parameters. Values with `undefined` are skipped. */
  query?: Record<string, string | number | undefined>;
  /** Resilience knobs for this specific call. */
  resilience: ResilienceConfig;
  /** Override base URL (kept for parity with other adapters; rarely needed). */
  baseUrl?: string;
  /** Optional AbortSignal for cooperative cancellation in tests. */
  signal?: AbortSignal;
}

/**
 * Issue a single Commission Factory Affiliate API request under the resilience policy.
 *
 * Why we don't validate response shapes with Zod: Commission Factory documents
 * field names but the set can vary across functions and account types. Treating
 * every field as possibly absent and preserving `rawNetworkData` is more robust
 * than a schema that breaks on drift.
 */
export async function commissionFactoryRequest<T>(
  input: CommissionFactoryRequestInput,
): Promise<T> {
  const ctx: WithResilienceContext = { network: SLUG, operation: input.operation };
  const base = input.baseUrl ?? COMMISSION_FACTORY_BASE_URL;

  return withResilience(
    ctx,
    async () => {
      // The API key is a query parameter, not a header (verified from the docs).
      const query = { ...(input.query ?? {}), apiKey: input.apiKey };
      const url = buildUrl(base, input.path, query);
      const init: RequestInit = {
        method: input.method ?? 'GET',
        headers: { Accept: 'application/json' },
      };
      if (input.signal) {
        init.signal = input.signal;
      }

      // Never log the URL with the key in it — redact the apiKey query parameter.
      log.debug(
        { path: input.path, method: init.method, operation: input.operation },
        'commission-factory request',
      );

      const res = await fetch(url, init);
      const rawBody = await res.text();

      if (!res.ok) {
        throw new HttpStatusError(
          res.status,
          rawBody,
          `Commission Factory ${input.operation} ${init.method} ${input.path} → HTTP ${res.status}`,
        );
      }

      if (rawBody.trim() === '') {
        return {} as T;
      }

      try {
        return JSON.parse(rawBody) as T;
      } catch (err) {
        throw new NetworkError(
          buildErrorEnvelope({
            type: 'network_api_error',
            network: SLUG,
            operation: input.operation,
            httpStatus: res.status,
            networkErrorBody: rawBody,
            message: `Commission Factory ${input.operation} returned HTTP ${res.status} with non-JSON body (parse error: ${(err as Error).message})`,
          }),
        );
      }
    },
    input.resilience,
  );
}

function buildUrl(
  base: string,
  pathname: string,
  query?: Record<string, string | number | undefined>,
): string {
  // The base URL carries the /V1/ segment; join relative paths against it.
  // A path like `/Affiliate/Transactions` resolves to
  // `https://api.commissionfactory.com/V1/Affiliate/Transactions`.
  const relative = pathname.startsWith('/') ? pathname.slice(1) : pathname;
  const baseWithSlash = base.endsWith('/') ? base : `${base}/`;
  const url = new URL(relative, baseWithSlash);
  if (query) {
    for (const [k, v] of Object.entries(query)) {
      if (v === undefined) continue;
      url.searchParams.set(k, String(v));
    }
  }
  return url.toString();
}

export { HttpStatusError };
