/**
 * Addrevenue adapter — publisher side, single-brand.
 *
 * Addrevenue is a Nordic affiliate network (primary market SE) that aggregates
 * 900+ advertisers. It exposes a versioned REST API documented at
 * https://addrevenue.io/en/developers, authenticated with a long-lived OAuth2
 * "lifetime" token generated by hand under Tools → API Tokens. We treat that
 * token as a static bearer secret — see `auth.ts` / `client.ts`.
 *
 * This adapter follows the Awin reference (`src/networks/awin/adapter.ts`)
 * end to end. The six cardinal rules from that file apply here too:
 *   1. Never call `fetch` directly — go through `addrevenueRequest`.
 *   2. Every failure round-trips through a NetworkErrorEnvelope (principle 4.1).
 *   3. Preserve the upstream payload verbatim in `rawNetworkData`.
 *   4. Normalise status enums to the canonical set; prefer 'other'/'unknown'
 *      to a wrong guess.
 *   5. Compute `ageDays` for every transaction (PRD §15.9).
 *   6. UK English in every user-visible string ("programme", not "program").
 *
 * --- Addrevenue API map (verify against https://addrevenue.io/en/developers) ---
 *
 *   GET /api/v2/advertisers
 *     → advertisers (our "programmes"). Returns `{ results: [...] }`.
 *   GET /api/v2/conversions?channelId=&startDate=&endDate=
 *     → transactions/conversions for the channel and window.
 *   GET /api/v2/clicks?channelId=&startDate=&endDate=
 *     → click-level rows for the channel and window.
 *   GET /api/v2/payments  /  GET /api/v2/invoices
 *     → settlement data (not surfaced by the seven canonical ops at v0.1).
 *
 * --- EXPERIMENTAL: shapes not yet verified against a live account ------------
 *
 * The developer reference is JS-rendered and bot-protected, so the exact field
 * names, pagination scheme, and amount unit below were inferred from Addrevenue's
 * documented tracking model and third-party integrations rather than confirmed
 * byte-for-byte against a tenant. Every transformer therefore reads keys
 * defensively and preserves the raw payload on `rawNetworkData`. The adapter
 * ships `claim_status: experimental` until a live acceptance test confirms them.
 */

import { addrevenueRequest } from './client.js';
import { verifyAuth as authVerify, validateCredential as authValidate } from './auth.js';
import { setupSteps } from './setup.js';
import { requireCredential, getCredential } from '../../shared/config.js';
import { buildErrorEnvelope, NetworkError } from '../../shared/errors.js';
import { DEFAULT_RESILIENCE } from '../../shared/resilience.js';
import { registerAdapter } from '../../shared/registry.js';
import { createLogger } from '../../shared/logging.js';
import {
  NotImplementedError,
  type Click,
  type ClickQuery,
  type CredentialValidationResult,
  type EarningsByProgramme,
  type EarningsByStatus,
  type EarningsSummary,
  type NetworkAdapter,
  type NetworkCapabilities,
  type NetworkMeta,
  type OperationCapability,
  type Programme,
  type ProgrammeQuery,
  type ProgrammeStatus,
  type ResilienceConfig,
  type ResilienceConfigMap,
  type SetupStep,
  type TrackingLink,
  type Transaction,
  type TransactionQuery,
  type TransactionStatus,
} from '../../shared/types.js';

const log = createLogger('addrevenue.adapter');

const SLUG = 'addrevenue';
const NAME = 'Addrevenue';

/**
 * Default reporting currency. Addrevenue's primary market is Sweden, so SEK is
 * the sensible fallback when a row omits an explicit currency. Per-row currency
 * is always preferred where present; this only fills the gap.
 */
const DEFAULT_CURRENCY = 'SEK';

const META: NetworkMeta = {
  slug: SLUG,
  name: NAME,
  baseUrl: 'https://addrevenue.io/api/v2',
  authModel: 'bearer',
  docsUrl: 'https://addrevenue.io/en/developers',
  adapterVersion: '0.1.0',
  lastVerified: '2026-06-05',
  // `experimental`: response shapes are inferred from the public documentation
  // and have not been validated against a live Addrevenue account at commit
  // time. Bump to `partial`/`production` after acceptance testing.
  claimStatus: 'experimental',
  knownLimitations: [
    'Experimental: Addrevenue API response shapes (field names, pagination, amount unit) are ' +
      'inferred from the public developer reference and have not been validated against a live ' +
      'account; transformers read defensively and preserve the raw payload on rawNetworkData.',
    'Amount unit is assumed to be the major currency unit (e.g. SEK, not öre) with a per-row ' +
      'currency field; this has not been confirmed against a live account.',
  ],
  supportsBrandOps: false,
  setupTimeEstimateMinutes: 5,
  setupRequiresApproval: false,
  side: 'publisher',
  credentialScope: 'single-brand',
};

// ---------------------------------------------------------------------------
// Resilience profile
// ---------------------------------------------------------------------------

/**
 * Transactions and clicks can return large windows; give them the same longer
 * profile Awin uses for its slow report engine. Everything else uses the
 * default (30s, 2 retries, retry on [429, 502, 503, 504]).
 */
const WIDE_WINDOW_RESILIENCE: ResilienceConfig = {
  ...DEFAULT_RESILIENCE,
  timeoutMs: 60_000,
  retries: 3,
};

const RESILIENCE: ResilienceConfigMap = {
  default: DEFAULT_RESILIENCE,
  listTransactions: WIDE_WINDOW_RESILIENCE,
  getEarningsSummary: WIDE_WINDOW_RESILIENCE,
  listClicks: WIDE_WINDOW_RESILIENCE,
};

// ---------------------------------------------------------------------------
// Addrevenue response shapes (deliberately minimal — see file header)
// ---------------------------------------------------------------------------

/** Addrevenue list endpoints wrap rows in `{ results: [...] }`. */
interface AddrevenueListEnvelope<T> {
  results?: T[];
}

interface AddrevenueAdvertiserRaw {
  id?: number | string;
  advertiserId?: number | string;
  name?: string;
  displayName?: string;
  market?: string; // ISO country, e.g. "SE"
  currency?: string;
  status?: string; // active | paused | pending | declined | ...
  relationship?: string; // joined | available | ...
  joined?: boolean;
  url?: string;
  website?: string;
  categories?: string[];
  category?: string;
  // Commission is exposed as a free-text or numeric provision depending on the
  // programme; we surface whichever is present as a description string.
  commission?: string | number;
  provision?: string | number;
}

interface AddrevenueConversionRaw {
  id?: number | string;
  conversionId?: number | string;
  advertiserId?: number | string;
  advertiserName?: string;
  channelId?: number | string;
  status?: string; // pending | approved | confirmed | rejected | paid | ...
  // Order value (gross sale) and the publisher's commission.
  value?: number;
  orderValue?: number;
  commission?: number;
  commissionAmount?: number;
  currency?: string;
  market?: string;
  // Dates — ISO 8601. Names vary; we read several.
  clickDate?: string;
  clickTime?: string;
  conversionDate?: string;
  conversionTime?: string;
  date?: string;
  createdAt?: string;
  approvedDate?: string;
  modifiedDate?: string;
  paidDate?: string;
  paymentDate?: string;
  paid?: boolean;
  orderId?: string;
  clickRef?: string;
  rejectionReason?: string;
  reason?: string;
}

interface AddrevenueClickRaw {
  id?: number | string;
  clickId?: number | string;
  advertiserId?: number | string;
  channelId?: number | string;
  date?: string;
  clickDate?: string;
  clickTime?: string;
  timestamp?: string;
  referrer?: string;
  referrerUrl?: string;
  landingPage?: string;
  destinationUrl?: string;
  targetUrl?: string;
  clickRef?: string;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Status normalisation: Addrevenue conversion status → canonical.
 *
 * Addrevenue uses words like `pending`, `approved`/`confirmed`, `rejected`, and
 * `paid`. We collapse to the canonical set:
 *
 *   pending                 → 'pending'
 *   approved / confirmed     → 'approved'
 *   rejected / cancelled     → 'reversed'  (the publisher did not get paid)
 *   paid                     → 'paid'
 *   anything else            → 'other'
 *
 * A `paid: true` flag (or a populated paid date) overrides the status string,
 * mirroring Awin's `paidToPublisher` handling — a conversion can stay
 * "approved" upstream after payment is issued. Unknown values map to 'other'
 * by design: we never invent a status the user did not see in Addrevenue.
 */
function mapConversionStatus(raw: AddrevenueConversionRaw): TransactionStatus {
  if (raw.paid === true || raw.paidDate || raw.paymentDate) return 'paid';
  switch ((raw.status ?? '').toLowerCase()) {
    case 'pending':
    case 'open':
      return 'pending';
    case 'approved':
    case 'confirmed':
    case 'accepted':
      return 'approved';
    case 'rejected':
    case 'declined':
    case 'cancelled':
    case 'canceled':
      return 'reversed';
    case 'paid':
      return 'paid';
    default:
      return 'other';
  }
}

/**
 * Status normalisation: Addrevenue advertiser state → canonical ProgrammeStatus.
 *
 *   joined / active          → 'joined'
 *   pending                  → 'pending'
 *   declined / rejected      → 'declined'
 *   available / notjoined    → 'available'
 *   paused / suspended       → 'suspended'
 *   anything else            → 'unknown'
 *
 * `joined: true` is honoured first because the listing exposes it as a boolean
 * alongside the status string. As with Awin we prefer 'unknown' to a wrong
 * guess when a new state appears.
 */
function mapAdvertiserStatus(raw: AddrevenueAdvertiserRaw): ProgrammeStatus {
  if (raw.joined === true) return 'joined';
  const s = (raw.status ?? raw.relationship ?? '').toLowerCase();
  if (s === 'joined' || s === 'active' || s === 'approved') return 'joined';
  if (s === 'pending') return 'pending';
  if (s === 'declined' || s === 'rejected' || s === 'refused') return 'declined';
  if (s === 'available' || s === 'notjoined' || s === 'open') return 'available';
  if (s === 'paused' || s === 'suspended' || s === 'inactive') return 'suspended';
  return 'unknown';
}

/**
 * Compute the age (in days) of a conversion at the moment this adapter
 * responded. PRD §15.9. We anchor on the approval date (when Addrevenue
 * confirmed the commission), falling back to the conversion date and finally a
 * generic date field — mirroring Awin's validationDate → transactionDate
 * preference so the unpaid-age affordance is meaningful.
 */
function computeAgeDays(raw: AddrevenueConversionRaw, now: Date = new Date()): number {
  const anchor =
    raw.approvedDate ??
    raw.conversionDate ??
    raw.conversionTime ??
    raw.date ??
    raw.createdAt;
  if (!anchor) return 0;
  const t = Date.parse(anchor);
  if (Number.isNaN(t)) return 0;
  const ms = now.getTime() - t;
  return Math.max(0, Math.floor(ms / (1000 * 60 * 60 * 24)));
}

function nullableIso(d?: string): string | undefined {
  if (!d) return undefined;
  const ts = Date.parse(d);
  return Number.isNaN(ts) ? undefined : new Date(ts).toISOString();
}

function numeric(...vals: Array<number | undefined>): number {
  for (const v of vals) {
    if (typeof v === 'number' && !Number.isNaN(v)) return v;
  }
  return 0;
}

/** Format a Date for Addrevenue's `startDate`/`endDate` query params (YYYY-MM-DD). */
function formatDate(d: Date): string {
  return d.toISOString().slice(0, 10);
}

// ---------------------------------------------------------------------------
// Transformers (Addrevenue raw → canonical domain types)
// ---------------------------------------------------------------------------

function toProgramme(raw: AddrevenueAdvertiserRaw): Programme {
  const id = String(raw.id ?? raw.advertiserId ?? '');
  const commissionText =
    raw.commission !== undefined
      ? String(raw.commission)
      : raw.provision !== undefined
        ? String(raw.provision)
        : undefined;
  const categories =
    raw.categories ?? (typeof raw.category === 'string' ? [raw.category] : undefined);
  return {
    id,
    name: raw.displayName ?? raw.name ?? `Addrevenue advertiser ${id}`,
    network: SLUG,
    status: mapAdvertiserStatus(raw),
    currency: raw.currency,
    commissionRate: commissionText
      ? { type: 'unknown', description: commissionText }
      : undefined,
    categories: categories?.filter((c): c is string => typeof c === 'string'),
    advertiserUrl: raw.url ?? raw.website,
    rawNetworkData: raw,
  };
}

function toTransaction(raw: AddrevenueConversionRaw, now: Date = new Date()): Transaction {
  const status = mapConversionStatus(raw);
  const commission = numeric(raw.commission, raw.commissionAmount);
  const sale = numeric(raw.orderValue, raw.value);
  const currency = raw.currency ?? DEFAULT_CURRENCY;

  const converted =
    nullableIso(raw.conversionDate ?? raw.conversionTime ?? raw.date ?? raw.createdAt) ??
    new Date(0).toISOString();

  return {
    id: String(raw.id ?? raw.conversionId ?? raw.orderId ?? ''),
    network: SLUG,
    programmeId: String(raw.advertiserId ?? ''),
    programmeName: raw.advertiserName ?? '',
    status,
    amount: sale,
    currency,
    commission,
    dateClicked: nullableIso(raw.clickDate ?? raw.clickTime),
    dateConverted: converted,
    dateApproved: nullableIso(raw.approvedDate ?? raw.modifiedDate),
    datePaid: nullableIso(raw.paidDate ?? raw.paymentDate),
    ageDays: computeAgeDays(raw, now),
    // PRD §15.10 — surface a reversal reason where Addrevenue provides one.
    reversalReason:
      status === 'reversed' ? raw.rejectionReason ?? raw.reason ?? undefined : undefined,
    rawNetworkData: raw,
  };
}

function toClick(raw: AddrevenueClickRaw): Click {
  const timestamp =
    nullableIso(raw.timestamp ?? raw.clickDate ?? raw.clickTime ?? raw.date) ??
    new Date(0).toISOString();
  return {
    id: String(raw.id ?? raw.clickId ?? ''),
    network: SLUG,
    programmeId: raw.advertiserId !== undefined ? String(raw.advertiserId) : undefined,
    timestamp,
    referrer: raw.referrer ?? raw.referrerUrl,
    destinationUrl: raw.destinationUrl ?? raw.targetUrl ?? raw.landingPage,
    rawNetworkData: raw,
  };
}

// ---------------------------------------------------------------------------
// The adapter itself
// ---------------------------------------------------------------------------

export class AddrevenueAdapter implements NetworkAdapter {
  readonly slug = SLUG;
  readonly name = NAME;
  readonly meta = META;
  readonly resilienceConfig = RESILIENCE;

  // -------------------------------------------------------------------------
  // listProgrammes (Addrevenue advertisers)
  // -------------------------------------------------------------------------

  /**
   * List Addrevenue advertisers (our "programmes").
   *
   * GET /advertisers returns `{ results: [...] }`. Addrevenue does not document
   * server-side search/status/category filters on this endpoint, so — like
   * Awin — we fetch the listing and filter client-side. `query.limit` is
   * applied last.
   */
  async listProgrammes(query?: ProgrammeQuery): Promise<Programme[]> {
    const token = requireCredential('ADDREVENUE_API_TOKEN', {
      network: SLUG,
      operation: 'listProgrammes',
      hint: 'Generate a lifetime token under Tools → API Tokens in the Addrevenue dashboard.',
    });

    const raw = await addrevenueRequest<
      AddrevenueListEnvelope<AddrevenueAdvertiserRaw> | AddrevenueAdvertiserRaw[]
    >({
      operation: 'listProgrammes',
      path: '/advertisers',
      token,
      query: { channelId: getCredential('ADDREVENUE_CHANNEL_ID') },
      resilience: RESILIENCE.listProgrammes ?? RESILIENCE.default,
    });

    const rows = extractResults(raw);
    let programmes = rows.map(toProgramme);

    if (query?.search) {
      const needle = query.search.toLowerCase();
      programmes = programmes.filter((p) => p.name.toLowerCase().includes(needle));
    }
    const statusFilter = toStatusList(query?.status);
    if (statusFilter && statusFilter.length > 0) {
      const set = new Set(statusFilter);
      programmes = programmes.filter((p) => set.has(p.status));
    }
    if (query?.categories && query.categories.length > 0) {
      const wanted = new Set(query.categories.map((c) => c.toLowerCase()));
      programmes = programmes.filter((p) =>
        (p.categories ?? []).some((c) => wanted.has(c.toLowerCase())),
      );
    }
    if (typeof query?.limit === 'number') {
      programmes = programmes.slice(0, query.limit);
    }

    return programmes;
  }

  // -------------------------------------------------------------------------
  // getProgramme
  // -------------------------------------------------------------------------

  /**
   * Fetch a single advertiser by ID.
   *
   * Addrevenue does not document a per-advertiser detail endpoint distinct from
   * the listing, so we fetch the listing and select the matching row. This
   * keeps us honest: if the advertiser is not in the channel's listing we throw
   * a network_api_error envelope rather than fabricating a stub.
   */
  async getProgramme(programmeId: string): Promise<Programme> {
    if (!programmeId || !/^\d+$/.test(programmeId)) {
      throw new NetworkError(
        buildErrorEnvelope({
          type: 'config_error',
          network: SLUG,
          operation: 'getProgramme',
          message: `Addrevenue advertiser IDs are numeric; received "${programmeId}".`,
          hint: 'List programmes first (affiliate_addrevenue_list_programmes) to find the correct id.',
        }),
      );
    }

    const programmes = await this.listProgrammes();
    const match = programmes.find((p) => p.id === programmeId);
    if (!match) {
      throw new NetworkError(
        buildErrorEnvelope({
          type: 'network_api_error',
          network: SLUG,
          operation: 'getProgramme',
          message: `Addrevenue advertiser ${programmeId} was not found in the channel's advertiser listing.`,
          hint: 'The advertiser may not be available to this channel. Use list_programmes to see available IDs.',
        }),
      );
    }
    return match;
  }

  // -------------------------------------------------------------------------
  // listTransactions (Addrevenue conversions)
  // -------------------------------------------------------------------------

  /**
   * List conversions across a date window with optional status / age /
   * programme filters.
   *
   *   GET /conversions?channelId=&startDate=YYYY-MM-DD&endDate=YYYY-MM-DD
   *
   * Addrevenue's documented window cap is not confirmed, so to stay within any
   * undocumented limit we chunk wide ranges into ≤31-day slices (the Awin
   * default) and concatenate. A 90-day window therefore makes 3 sequential
   * calls; resilience applies per-call.
   *
   * Filtering by status / programme / age is applied client-side after the
   * fetch (the endpoint's server-side filter support is unverified). Age
   * filters run AFTER status filtering so `{ status: 'approved', minAgeDays:
   * 180 }` is meaningful (PRD §15.9). Reversed conversions are returned unless
   * excluded, with `reversalReason` populated (PRD §15.10).
   */
  async listTransactions(query?: TransactionQuery): Promise<Transaction[]> {
    const token = requireCredential('ADDREVENUE_API_TOKEN', {
      network: SLUG,
      operation: 'listTransactions',
      hint: 'Generate a lifetime token under Tools → API Tokens in the Addrevenue dashboard.',
    });
    const channelId = requireCredential('ADDREVENUE_CHANNEL_ID', {
      network: SLUG,
      operation: 'listTransactions',
      hint: 'Set ADDREVENUE_CHANNEL_ID (the `c` value from your tracking links). Reporting is scoped per channel.',
    });

    const now = new Date();
    const to = query?.to ? new Date(query.to) : now;
    const from = query?.from
      ? new Date(query.from)
      : new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000);

    const slices = chunkDateRange(from, to, 31);

    const allRaw: AddrevenueConversionRaw[] = [];
    for (const slice of slices) {
      const chunk = await addrevenueRequest<
        AddrevenueListEnvelope<AddrevenueConversionRaw> | AddrevenueConversionRaw[]
      >({
        operation: 'listTransactions',
        path: '/conversions',
        token,
        query: {
          channelId,
          startDate: formatDate(slice.start),
          endDate: formatDate(slice.end),
        },
        resilience: RESILIENCE.listTransactions ?? RESILIENCE.default,
      });
      allRaw.push(...extractResults(chunk));
    }

    let transactions = allRaw.map((r) => toTransaction(r, now));

    if (query?.programmeId) {
      transactions = transactions.filter((t) => t.programmeId === query.programmeId);
    }

    const statusFilter = toTransactionStatusList(query?.status);
    if (statusFilter && statusFilter.length > 0) {
      const set = new Set(statusFilter);
      transactions = transactions.filter((t) => set.has(t.status));
    }

    const minAge = query?.minAgeDays;
    if (typeof minAge === 'number') {
      transactions = transactions.filter((t) => t.ageDays >= minAge);
    }
    const maxAge = query?.maxAgeDays;
    if (typeof maxAge === 'number') {
      transactions = transactions.filter((t) => t.ageDays <= maxAge);
    }

    if (typeof query?.limit === 'number') {
      transactions = transactions.slice(0, query.limit);
    }

    return transactions;
  }

  // -------------------------------------------------------------------------
  // getEarningsSummary
  // -------------------------------------------------------------------------

  /**
   * Aggregate conversions into an earnings summary.
   *
   * Derived from `listTransactions` (not a separate report endpoint) so the
   * user can reproduce the figures by listing the same transactions — the
   * single-source-of-truth argument from Awin's getEarningsSummary applies
   * verbatim. We never pass `limit` through; a limited summary undercounts
   * (principle 4.1).
   */
  async getEarningsSummary(query?: TransactionQuery): Promise<EarningsSummary> {
    const now = new Date();
    const from = query?.from ?? new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000).toISOString();
    const to = query?.to ?? now.toISOString();

    const txns = await this.listTransactions({ ...query, from, to, limit: undefined });

    const byProgrammeMap = new Map<string, EarningsByProgramme>();
    const byStatus: EarningsByStatus = {
      pending: 0,
      approved: 0,
      reversed: 0,
      paid: 0,
      other: 0,
      currency: DEFAULT_CURRENCY,
    };

    let totalEarnings = 0;
    let firstCurrency: string | undefined;
    let oldestUnpaidAgeDays: number | undefined;

    for (const t of txns) {
      if (!firstCurrency) firstCurrency = t.currency;

      byStatus[t.status] = (byStatus[t.status] ?? 0) + t.commission;
      totalEarnings += t.commission;

      const key = t.programmeId || '__unknown';
      const existing = byProgrammeMap.get(key);
      if (existing) {
        existing.total += t.commission;
        existing.transactionCount += 1;
      } else {
        byProgrammeMap.set(key, {
          programmeId: key,
          programmeName: t.programmeName || `Addrevenue advertiser ${key}`,
          total: t.commission,
          currency: t.currency,
          transactionCount: 1,
        });
      }

      if (t.status === 'pending' || t.status === 'approved') {
        if (oldestUnpaidAgeDays === undefined || t.ageDays > oldestUnpaidAgeDays) {
          oldestUnpaidAgeDays = t.ageDays;
        }
      }
    }

    if (firstCurrency) byStatus.currency = firstCurrency;

    return {
      network: SLUG,
      totalEarnings,
      currency: firstCurrency ?? DEFAULT_CURRENCY,
      byProgramme: [...byProgrammeMap.values()],
      byStatus,
      oldestUnpaidAgeDays,
      periodFrom: from,
      periodTo: to,
    };
  }

  // -------------------------------------------------------------------------
  // listClicks (Addrevenue DOES expose clicks)
  // -------------------------------------------------------------------------

  /**
   * List click-level rows for the channel.
   *
   *   GET /clicks?channelId=&startDate=YYYY-MM-DD&endDate=YYYY-MM-DD
   *
   * Unlike Awin, Addrevenue exposes clicks via its publisher API (this is one
   * of the data types third-party aggregators collect from it). We chunk wide
   * windows the same way as transactions and apply programme/limit filters
   * client-side.
   */
  async listClicks(query?: ClickQuery): Promise<Click[]> {
    const token = requireCredential('ADDREVENUE_API_TOKEN', {
      network: SLUG,
      operation: 'listClicks',
      hint: 'Generate a lifetime token under Tools → API Tokens in the Addrevenue dashboard.',
    });
    const channelId = requireCredential('ADDREVENUE_CHANNEL_ID', {
      network: SLUG,
      operation: 'listClicks',
      hint: 'Set ADDREVENUE_CHANNEL_ID (the `c` value from your tracking links). Click reporting is scoped per channel.',
    });

    const now = new Date();
    const to = query?.to ? new Date(query.to) : now;
    const from = query?.from
      ? new Date(query.from)
      : new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000);

    const slices = chunkDateRange(from, to, 31);

    const allRaw: AddrevenueClickRaw[] = [];
    for (const slice of slices) {
      const chunk = await addrevenueRequest<
        AddrevenueListEnvelope<AddrevenueClickRaw> | AddrevenueClickRaw[]
      >({
        operation: 'listClicks',
        path: '/clicks',
        token,
        query: {
          channelId,
          startDate: formatDate(slice.start),
          endDate: formatDate(slice.end),
        },
        resilience: RESILIENCE.listClicks ?? RESILIENCE.default,
      });
      allRaw.push(...extractResults(chunk));
    }

    let clicks = allRaw.map(toClick);

    if (query?.programmeId) {
      clicks = clicks.filter((c) => c.programmeId === query.programmeId);
    }
    if (typeof query?.limit === 'number') {
      clicks = clicks.slice(0, query.limit);
    }

    return clicks;
  }

  // -------------------------------------------------------------------------
  // generateTrackingLink (deterministic)
  // -------------------------------------------------------------------------

  /**
   * Construct an Addrevenue tracking link.
   *
   * Addrevenue's documented redirect format is deterministic:
   *
   *   https://addrevenue.io/t
   *     ?c={channelId}
   *     &a={advertiserId}
   *     &url={destinationUrl, URL-encoded}
   *
   * (`r` is the optional sub-id / clickRef; we omit it.) Because the scheme is
   * documented and stable, we build the URL locally rather than calling the API
   * — the Awin rationale applies. We still require the token to be configured
   * so a half-configured environment fails at link-generation time.
   *
   * `programmeId` is the advertiser ID (`a`); the channel ID comes from
   * ADDREVENUE_CHANNEL_ID. Both are required to build a working link.
   */
  async generateTrackingLink(input: {
    programmeId: string;
    destinationUrl: string;
  }): Promise<TrackingLink> {
    if (!input.programmeId) {
      throw new NetworkError(
        buildErrorEnvelope({
          type: 'config_error',
          network: SLUG,
          operation: 'generateTrackingLink',
          message: 'Addrevenue tracking links require the advertiser (programme) ID.',
          hint: 'Pass `programmeId`. Use affiliate_addrevenue_list_programmes to discover the advertiser ID.',
        }),
      );
    }
    if (!input.destinationUrl) {
      throw new NetworkError(
        buildErrorEnvelope({
          type: 'config_error',
          network: SLUG,
          operation: 'generateTrackingLink',
          message: 'destinationUrl is required.',
          hint: 'Pass the full URL of the merchant page you want to link to.',
        }),
      );
    }

    requireCredential('ADDREVENUE_API_TOKEN', {
      network: SLUG,
      operation: 'generateTrackingLink',
      hint: 'Generate a lifetime token under Tools → API Tokens in the Addrevenue dashboard.',
    });
    const channelId = requireCredential('ADDREVENUE_CHANNEL_ID', {
      network: SLUG,
      operation: 'generateTrackingLink',
      hint: 'Set ADDREVENUE_CHANNEL_ID (the `c` value from your tracking links). It identifies your channel in the link.',
    });

    const encoded = encodeURIComponent(input.destinationUrl);
    const trackingUrl =
      `https://addrevenue.io/t` +
      `?c=${encodeURIComponent(channelId)}` +
      `&a=${encodeURIComponent(input.programmeId)}` +
      `&url=${encoded}`;

    return {
      network: SLUG,
      destinationUrl: input.destinationUrl,
      trackingUrl,
      programmeId: input.programmeId,
      createdAt: new Date().toISOString(),
      rawNetworkData: {
        format: 'addrevenue.io/t deterministic construction',
        c: channelId,
        a: input.programmeId,
        url: input.destinationUrl,
      },
    };
  }

  // -------------------------------------------------------------------------
  // verifyAuth
  // -------------------------------------------------------------------------

  async verifyAuth(): Promise<{ ok: true; identity?: string } | { ok: false; reason: string }> {
    const result = await authVerify();
    if (result.ok) {
      return result.identity ? { ok: true, identity: result.identity } : { ok: true };
    }
    return { ok: false, reason: result.reason };
  }

  // -------------------------------------------------------------------------
  // Admin operations (v0.2 scaffolds)
  // -------------------------------------------------------------------------

  async listPublishers(): Promise<never> {
    throw new NotImplementedError('Brand-side operations are scaffolded for v0.2');
  }
  async listPublisherSectors(): Promise<never> {
    throw new NotImplementedError('Brand-side operations are scaffolded for v0.2');
  }

  // -------------------------------------------------------------------------
  // validateCredential / setupSteps
  // -------------------------------------------------------------------------

  async validateCredential(field: string, value: string): Promise<CredentialValidationResult> {
    return authValidate(field, value);
  }

  setupSteps(): SetupStep[] {
    return setupSteps();
  }

  // -------------------------------------------------------------------------
  // capabilitiesCheck
  // -------------------------------------------------------------------------

  async capabilitiesCheck(): Promise<NetworkCapabilities> {
    const operations: Record<string, OperationCapability> = {};

    const probe = async (name: string, fn: () => Promise<unknown>): Promise<void> => {
      const start = Date.now();
      try {
        const result = await fn();
        const sampleSize = Array.isArray(result) ? result.length : 1;
        operations[name] = {
          supported: true,
          latencyMs: Date.now() - start,
          sampleSize,
          // Per-op experimental flag: shapes are inferred, not live-verified.
          claimStatus: 'experimental',
        };
      } catch (err) {
        operations[name] = {
          supported: false,
          latencyMs: Date.now() - start,
          note: err instanceof Error ? err.message : String(err),
        };
      }
    };

    await probe('listProgrammes', () => this.listProgrammes({ limit: 1 }));
    await probe('listTransactions', () => this.listTransactions({ limit: 1 }));
    await probe('getEarningsSummary', () => this.getEarningsSummary({ limit: 1 }));
    await probe('listClicks', () => this.listClicks({ limit: 1 }));
    await probe('verifyAuth', () => this.verifyAuth());

    operations['generateTrackingLink'] = {
      supported: true,
      note: 'Deterministic URL construction; no live probe.',
      claimStatus: 'experimental',
    };
    operations['getProgramme'] = {
      supported: true,
      note: 'Selects from the advertiser listing; not probed automatically.',
      claimStatus: 'experimental',
    };

    return {
      network: SLUG,
      generatedAt: new Date().toISOString(),
      operations,
      knownLimitations: META.knownLimitations,
    };
  }
}

// ---------------------------------------------------------------------------
// Module-level registration (see Awin's adapter.ts for the rationale).
// ---------------------------------------------------------------------------

export const addrevenueAdapter = new AddrevenueAdapter();
registerAdapter(addrevenueAdapter);

// ---------------------------------------------------------------------------
// Local helpers
// ---------------------------------------------------------------------------

/**
 * Unwrap Addrevenue's `{ results: [...] }` envelope, tolerating a bare array.
 */
function extractResults<T>(raw: AddrevenueListEnvelope<T> | T[] | undefined): T[] {
  if (Array.isArray(raw)) return raw;
  if (raw && Array.isArray(raw.results)) return raw.results;
  return [];
}

function toStatusList(v?: ProgrammeStatus | ProgrammeStatus[]): ProgrammeStatus[] | undefined {
  if (v === undefined) return undefined;
  return Array.isArray(v) ? v : [v];
}

function toTransactionStatusList(
  v?: TransactionStatus | TransactionStatus[],
): TransactionStatus[] | undefined {
  if (v === undefined) return undefined;
  return Array.isArray(v) ? v : [v];
}

interface DateSlice {
  start: Date;
  end: Date;
}

/**
 * Split `[from, to]` into ≤`maxDays`-day chunks. Mirrors Awin's chunker so wide
 * windows are handled by the adapter rather than pushed onto callers. Returns
 * at least one (possibly zero-width) slice so the call shape stays predictable.
 */
function chunkDateRange(from: Date, to: Date, maxDays: number): DateSlice[] {
  if (Number.isNaN(from.getTime()) || Number.isNaN(to.getTime())) return [{ start: from, end: to }];
  if (from >= to) return [{ start: from, end: to }];

  const slices: DateSlice[] = [];
  const stepMs = maxDays * 24 * 60 * 60 * 1000;
  let cursor = from.getTime();
  const endMs = to.getTime();

  while (cursor < endMs) {
    const sliceEnd = Math.min(cursor + stepMs, endMs);
    slices.push({ start: new Date(cursor), end: new Date(sliceEnd) });
    cursor = sliceEnd;
  }
  return slices;
}

// Internal test helpers — exported under `_` so they don't appear in the
// public adapter surface.
export const _internals = {
  mapConversionStatus,
  mapAdvertiserStatus,
  computeAgeDays,
  toTransaction,
  toProgramme,
  toClick,
  chunkDateRange,
  formatDate,
  extractResults,
};

// Silence the unused-import lint for the logger when noUnusedLocals is on.
void log;
