/**
 * Commission Factory advertiser (merchant/brand-side) adapter.
 *
 * READ-ONLY at v0.1. Mirrors the impact-advertiser reference. The HTTP client
 * (./client.ts) refuses any non-GET method so this adapter cannot ship a write.
 *
 * --- Credential model ---------------------------------------------------------
 *
 * Commission Factory authenticates with a single API key, generated by the
 * account holder under their MERCHANT Account Settings, passed as the `apiKey`
 * QUERY PARAMETER on every request.
 *   Source: https://dev.commissionfactory.com/V1/GeneratingApiKeys/
 *           https://dev.commissionfactory.com/V1/ (Getting Started)
 *
 * The merchant key is issued under ONE merchant account and addresses only that
 * merchant's data. There is no merchant-side "list my accounts" endpoint, so at
 * runtime the key effectively addresses a single brand. We nonetheless declare
 * `credentialScope: 'multi-brand'` and implement `listBrands()` (required for
 * the advertiser surface): it returns exactly one DiscoveredBrand — the merchant
 * the key addresses — so the brand resolver and tool generator behave uniformly
 * with the other advertiser adapters (Impact, CJ). The single-merchant reality
 * is documented in `known_limitations`.
 *   BLOCKED(verify): whether any merchant key can ever address more than one
 *   merchant. Public docs describe one key per merchant Account Settings; a live
 *   account is required to confirm there is no multi-merchant arrangement.
 *
 * --- Operations ---------------------------------------------------------------
 *
 *   listBrands              → single synthetic entry from the merchant id hint,
 *                             or derived from a sample transaction's MerchantId.
 *   verifyAuth              → GET /Merchant/Transactions over a 1-day window.
 *   listProgrammes          → GET /Merchant/Promotions (the merchant's own
 *                             promotions/campaigns). BLOCKED(verify): the
 *                             merchant surface exposes Promotions rather than a
 *                             distinct "campaigns" list; mapped to Programme.
 *   listTransactions        → GET /Merchant/Transactions (brand-scoped via ctx).
 *   getProgrammePerformance → per-publisher rollup of /Merchant/Transactions
 *                             grouped by AffiliateId.
 *
 * Operations NOT in scope at v0.1 (throw NotImplementedError):
 *   getProgramme, getEarningsSummary, listClicks, generateTrackingLink,
 *   listPublishers, listPublisherSectors.
 *
 * --- Merchant Transaction fields (from docs) ----------------------------------
 *   { Id, DateCreated, DateModified, AffiliateId, AffiliateContactName,
 *     AffiliateBusinessName, SaleValue, Commission, ReportedCurrencyCode,
 *     Status, Status2, Paid, VoidReason, OrderId, ... }
 *   Source: https://dev.commissionfactory.com/V1/Merchant/Types/Transaction/
 *           https://dev.commissionfactory.com/V1/Merchant/Functions/GetTransactions/
 *           https://dev.commissionfactory.com/V1/Merchant/Types/TransactionStatus2/
 *
 * --- Cardinal rules (non-negotiable) ------------------------------------------
 *   1. Never call `fetch` outside `client.ts`. Use `commissionFactoryAdvertiserRequest`.
 *   2. Every failure round-trips through a `NetworkErrorEnvelope`. Never swallow.
 *   3. Preserve raw payloads in `rawNetworkData` on every domain object.
 *   4. Normalise status enums. See `mapTransactionStatus` / `mapPerfStatus`.
 *      Prefer `other`/`pending` over a wrong guess; raw is preserved.
 *   5. Inject `now` into date helpers so tests are deterministic.
 *   6. Read credentials via `requireApiKey` (which uses requireCredential) —
 *      never `process.env` directly outside tests.
 *   7. UK English. "programme", not "program".
 */

import { commissionFactoryAdvertiserRequest } from './client.js';
import {
  verifyAuth as authVerify,
  validateCredential as authValidate,
  requireApiKey,
  optionalMerchantId,
  SLUG,
} from './auth.js';
import { setupSteps } from './setup.js';
import { buildErrorEnvelope, NetworkError } from '../../shared/errors.js';
import { DEFAULT_RESILIENCE } from '../../shared/resilience.js';
import { registerAdapter } from '../../shared/registry.js';
import { createLogger } from '../../shared/logging.js';
import {
  NotImplementedError,
  type AdapterCallContext,
  type Click,
  type ClickQuery,
  type CredentialValidationResult,
  type DiscoveredBrand,
  type EarningsSummary,
  type NetworkAdapter,
  type NetworkCapabilities,
  type NetworkMeta,
  type OperationCapability,
  type Programme,
  type ProgrammePerformanceQuery,
  type ProgrammePerformanceRow,
  type ProgrammeQuery,
  type ProgrammeStatus,
  type ResilienceConfig,
  type ResilienceConfigMap,
  type SetupStep,
  type TrackingLink,
  type Transaction,
  type TransactionQuery,
  type TransactionStatus,
} from '../../shared/types.js';

const log = createLogger('commission-factory-advertiser.adapter');
const NAME = 'Commission Factory (advertiser)';

const META: NetworkMeta = {
  slug: SLUG,
  name: NAME,
  baseUrl: 'https://api.commissionfactory.com/V1/',
  authModel: 'custom',
  docsUrl: 'https://dev.commissionfactory.com/V1/',
  adapterVersion: '0.1.0',
  lastVerified: '2026-06-04',
  claimStatus: 'experimental',
  knownLimitations: [
    'Adapter built from public API documentation; not yet verified against a live account.',
    'Read-only at v0.1. The adapter refuses any non-GET HTTP method client-side.',
    'A merchant API key addresses exactly one merchant; the merchant surface has no "list my accounts" endpoint. `listBrands()` therefore returns a single brand. credential_scope is declared multi-brand for uniformity with the other advertiser adapters.',
    'getProgrammePerformance is a client-side per-publisher rollup of GET /Merchant/Transactions grouped by AffiliateId. Clicks are not reported on the merchant transactions surface, so per-row clicks are 0.',
    'Pagination parameters for GET /Merchant/Transactions are not documented publicly; the adapter requests the full date window in a single call. BLOCKED(verify) against a live account.',
  ],
  supportsBrandOps: true,
  setupTimeEstimateMinutes: 7,
  setupRequiresApproval: false,
  side: 'advertiser',
  credentialScope: 'multi-brand',
};

// ---------------------------------------------------------------------------
// Resilience profile
// ---------------------------------------------------------------------------

const TRANSACTIONS_RESILIENCE: ResilienceConfig = {
  ...DEFAULT_RESILIENCE,
  timeoutMs: 60_000,
  retries: 3,
};

const RESILIENCE: ResilienceConfigMap = {
  default: DEFAULT_RESILIENCE,
  listTransactions: TRANSACTIONS_RESILIENCE,
  getProgrammePerformance: TRANSACTIONS_RESILIENCE,
};

// ---------------------------------------------------------------------------
// Raw shapes
// ---------------------------------------------------------------------------

interface CfMerchantTransactionRaw {
  Id?: string | number;
  DateCreated?: string;
  DateModified?: string;
  OrderDate?: string;
  MerchantId?: string | number;
  MerchantName?: string;
  AffiliateId?: string | number;
  AffiliateContactName?: string;
  AffiliateBusinessName?: string;
  SaleValue?: number | string;
  ReportedSaleValue?: number | string;
  Commission?: number | string;
  ReportedCurrencyCode?: string;
  CurrencyCode?: string;
  Currency?: string;
  Status?: string;
  Status2?: string; // TransactionStatus2: Pending | Confirmed | Declined | Void | Paid
  Paid?: boolean | string;
  VoidReason?: string;
  OrderId?: string;
}

interface CfMerchantTransactionArrayRaw {
  Items?: CfMerchantTransactionRaw[];
  Transactions?: CfMerchantTransactionRaw[];
}

interface CfMerchantPromotionRaw {
  Id?: string | number;
  Name?: string;
  Title?: string;
  Status?: string;
  StartDate?: string;
  EndDate?: string;
  Url?: string;
  LandingPageUrl?: string;
}

interface CfMerchantPromotionArrayRaw {
  Items?: CfMerchantPromotionRaw[];
  Promotions?: CfMerchantPromotionRaw[];
}

// ---------------------------------------------------------------------------
// Helpers — ctx, conversions
// ---------------------------------------------------------------------------

/**
 * Require an `AdapterCallContext` on brand-scoped operations. We throw a
 * `config_error` envelope so the user sees a clear "this op needs `brand`"
 * rather than a runtime TypeError when ctx is missing — this can happen if a
 * future caller bypasses the tool dispatcher.
 *
 * Because a merchant key addresses one merchant, the `networkBrandId` is mostly
 * informational here; we still require it so the advertiser contract is
 * consistent across networks.
 */
function requireCtx(operation: string, ctx?: AdapterCallContext): AdapterCallContext {
  if (!ctx || !ctx.networkBrandId) {
    throw new NetworkError(
      buildErrorEnvelope({
        type: 'config_error',
        network: SLUG,
        operation,
        message: `Commission Factory advertiser ${operation} requires a brand context (networkBrandId).`,
        hint:
          'Advertiser-side tools require a `brand` argument that the dispatcher resolves to a ' +
          'networkBrandId via brands.json. Run `affiliate-networks-mcp setup commission-factory-advertiser` ' +
          'and bind the merchant as a brand.',
      }),
    );
  }
  return ctx;
}

function toAmount(v: number | string | undefined): number {
  if (v === undefined || v === null) return 0;
  const n = typeof v === 'number' ? v : parseFloat(String(v));
  return Number.isFinite(n) ? n : 0;
}

function nullableIso(d?: string | null): string | undefined {
  if (!d) return undefined;
  const ts = Date.parse(d);
  return Number.isNaN(ts) ? undefined : new Date(ts).toISOString();
}

function currencyOf(raw: CfMerchantTransactionRaw): string {
  return raw.ReportedCurrencyCode ?? raw.CurrencyCode ?? raw.Currency ?? 'AUD';
}

function computeAgeDays(raw: CfMerchantTransactionRaw, now: Date = new Date()): number {
  const anchor = raw.OrderDate ?? raw.DateCreated;
  if (!anchor) return 0;
  const t = Date.parse(anchor);
  if (Number.isNaN(t)) return 0;
  const ms = now.getTime() - t;
  return Math.max(0, Math.floor(ms / (1000 * 60 * 60 * 24)));
}

// ---------------------------------------------------------------------------
// Status mapping
// ---------------------------------------------------------------------------

/**
 * Map Commission Factory's TransactionStatus2 (preferred) — falling back to the
 * deprecated TransactionStatus — to the canonical TransactionStatus.
 *   Source: https://dev.commissionfactory.com/V1/Merchant/Types/TransactionStatus2/
 *
 *   Pending           → 'pending'   (open for validation)
 *   Confirmed         → 'approved'  (validated, not yet paid out)
 *   Paid              → 'paid'      (settled / invoiced)
 *   Declined / Void   → 'reversed'  (the sale did not pay out)
 *   anything else     → 'other'
 *
 * Verbatim status is preserved in `rawNetworkData`.
 */
function mapTransactionStatus(raw: CfMerchantTransactionRaw): TransactionStatus {
  const s = String(raw.Status2 ?? raw.Status ?? '').toLowerCase().trim();
  if (s === 'pending') return 'pending';
  if (s === 'confirmed' || s === 'approved' || s === 'accepted') return 'approved';
  if (s === 'paid') return 'paid';
  if (s === 'declined' || s === 'void' || s === 'voided' || s === 'reversed' || s === 'rejected') {
    return 'reversed';
  }
  return 'other';
}

/**
 * Map a transaction status to the THREE-state programme-performance status.
 * `ProgrammePerformanceRow.status` only allows pending|approved|reversed, so
 * 'paid' folds into 'approved' (a paid transaction was approved) and 'other'
 * folds conservatively into 'pending'.
 */
function mapPerfStatus(raw: CfMerchantTransactionRaw): ProgrammePerformanceRow['status'] {
  const s = mapTransactionStatus(raw);
  if (s === 'approved' || s === 'paid') return 'approved';
  if (s === 'reversed') return 'reversed';
  return 'pending';
}

function mapPromotionStatus(raw: CfMerchantPromotionRaw): ProgrammeStatus {
  const s = String(raw.Status ?? '').toLowerCase().trim();
  if (s === 'active' || s === 'live' || s === 'approved' || s === 'enabled') return 'joined';
  if (s === 'pending') return 'pending';
  if (s === 'paused' || s === 'suspended' || s === 'expired' || s === 'inactive' || s === 'disabled') {
    return 'suspended';
  }
  if (s === 'declined' || s === 'rejected') return 'declined';
  return 'unknown';
}

// ---------------------------------------------------------------------------
// Transformers
// ---------------------------------------------------------------------------

function toTransaction(raw: CfMerchantTransactionRaw, now: Date = new Date()): Transaction {
  const status = mapTransactionStatus(raw);
  const sale = toAmount(raw.SaleValue ?? raw.ReportedSaleValue);
  const commission = toAmount(raw.Commission);
  const currency = currencyOf(raw);

  const orderDate =
    nullableIso(raw.OrderDate) ?? nullableIso(raw.DateCreated) ?? new Date(0).toISOString();
  // Commission Factory does not expose an approval timestamp distinct from
  // DateModified; surface DateModified as the approved/paid date only when the
  // transaction is approved or paid, otherwise leave it undefined.
  const approvedDate =
    status === 'approved' || status === 'paid' ? nullableIso(raw.DateModified) : undefined;
  const paidDate = status === 'paid' ? nullableIso(raw.DateModified) : undefined;

  return {
    id: String(raw.Id ?? ''),
    network: SLUG,
    programmeId: String(raw.MerchantId ?? ''),
    programmeName: raw.MerchantName ?? `Commission Factory merchant ${raw.MerchantId ?? ''}`,
    status,
    amount: sale,
    currency,
    commission,
    dateClicked: undefined,
    dateConverted: orderDate,
    dateApproved: approvedDate,
    datePaid: paidDate,
    ageDays: computeAgeDays(raw, now),
    reversalReason: status === 'reversed' ? raw.VoidReason ?? undefined : undefined,
    rawNetworkData: raw,
  };
}

function toProgramme(raw: CfMerchantPromotionRaw): Programme {
  const id = String(raw.Id ?? '');
  return {
    id,
    name: raw.Name ?? raw.Title ?? `Commission Factory promotion ${id}`,
    network: SLUG,
    status: mapPromotionStatus(raw),
    advertiserUrl: raw.LandingPageUrl ?? raw.Url,
    rawNetworkData: raw,
  };
}

/**
 * Roll up an array of merchant transactions into one ProgrammePerformanceRow
 * per (affiliate, status, date). The merchant transactions surface reports
 * conversions, sale value and commission per transaction but NOT clicks, so
 * `clicks` is always 0.
 *
 * `date` is the conversion date (OrderDate / DateCreated) truncated to
 * yyyy-mm-dd. Grouping by date keeps the row shape honest (one period per row)
 * rather than collapsing a whole window into one synthetic row.
 */
function rollupByAffiliate(
  txns: CfMerchantTransactionRaw[],
  now: Date = new Date(),
): ProgrammePerformanceRow[] {
  const groups = new Map<string, ProgrammePerformanceRow>();
  for (const raw of txns) {
    const publisherId = String(raw.AffiliateId ?? '');
    const publisherName = raw.AffiliateBusinessName ?? raw.AffiliateContactName ?? '';
    const status = mapPerfStatus(raw);
    const iso = nullableIso(raw.OrderDate) ?? nullableIso(raw.DateCreated);
    const date = iso ? iso.slice(0, 10) : '';
    const currency = currencyOf(raw);
    const key = `${publisherId}|${status}|${date}`;

    let row = groups.get(key);
    if (!row) {
      row = {
        date,
        publisherId,
        publisherName,
        clicks: 0,
        conversions: 0,
        grossSale: 0,
        commission: 0,
        currency,
        status,
        // Preserve the contributing raw rows so the operator can drill in.
        rawNetworkData: [] as CfMerchantTransactionRaw[],
      };
      groups.set(key, row);
    }
    row.conversions += 1;
    row.grossSale += toAmount(raw.SaleValue ?? raw.ReportedSaleValue);
    row.commission += toAmount(raw.Commission);
    if (!row.publisherName && publisherName) row.publisherName = publisherName;
    (row.rawNetworkData as CfMerchantTransactionRaw[]).push(raw);
  }
  void now;
  return [...groups.values()];
}

function toDiscoveredBrand(id: string, displayName: string): DiscoveredBrand {
  return { networkBrandId: id, displayName, apiEnabled: true };
}

// ---------------------------------------------------------------------------
// Envelope extraction
// ---------------------------------------------------------------------------

function extractTransactions(
  env: CfMerchantTransactionArrayRaw | CfMerchantTransactionRaw[],
): CfMerchantTransactionRaw[] {
  if (Array.isArray(env)) return env;
  return env.Items ?? env.Transactions ?? [];
}

function extractPromotions(
  env: CfMerchantPromotionArrayRaw | CfMerchantPromotionRaw[],
): CfMerchantPromotionRaw[] {
  if (Array.isArray(env)) return env;
  return env.Items ?? env.Promotions ?? [];
}

// ---------------------------------------------------------------------------
// The adapter
// ---------------------------------------------------------------------------

export class CommissionFactoryAdvertiserAdapter implements NetworkAdapter {
  readonly slug = SLUG;
  readonly name = NAME;
  readonly meta = META;
  readonly resilienceConfig = RESILIENCE;

  /** Test seam: inject a clock used by date helpers. */
  private readonly now: () => Date;

  constructor(opts: { now?: () => Date } = {}) {
    this.now = opts.now ?? (() => new Date());
  }

  // -------------------------------------------------------------------------
  // listBrands — the multi-brand-discovery hook for the wizard.
  // -------------------------------------------------------------------------

  /**
   * A merchant key addresses one merchant. We return a single DiscoveredBrand:
   *   - networkBrandId / displayName from the optional MERCHANT_ID hint when set;
   *   - otherwise derived from a sample transaction's MerchantId / MerchantName
   *     over a recent 30-day window;
   *   - otherwise a synthesised fingerprint label as a last resort.
   *
   * BLOCKED(verify): whether a single merchant key can ever address more than
   * one merchant. Public docs describe one key per merchant Account Settings.
   */
  async listBrands(): Promise<DiscoveredBrand[]> {
    const apiKey = requireApiKey('listBrands');
    const hintId = optionalMerchantId();
    if (hintId) {
      return [toDiscoveredBrand(hintId, `Commission Factory merchant ${hintId}`)];
    }

    // Derive from a sample transaction over the last 30 days.
    const now = this.now();
    const from = new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000);
    const iso = (d: Date): string => d.toISOString().slice(0, 10);
    try {
      const env = await commissionFactoryAdvertiserRequest<
        CfMerchantTransactionArrayRaw | CfMerchantTransactionRaw[]
      >({
        operation: 'listBrands',
        path: '/Merchant/Transactions',
        apiKey,
        query: { fromDate: iso(from), toDate: iso(now) },
        resilience: RESILIENCE.default,
      });
      const txns = extractTransactions(env);
      const sample = txns.find((t) => t.MerchantId !== undefined);
      if (sample && sample.MerchantId !== undefined) {
        const id = String(sample.MerchantId);
        const name = sample.MerchantName ?? `Commission Factory merchant ${id}`;
        return [toDiscoveredBrand(id, name)];
      }
    } catch (err) {
      // Discovery is best-effort: a sparse account (no recent transactions)
      // must not fail the whole flow. Fall back to a synthetic label.
      log.warn(
        { err: err instanceof Error ? err.message : String(err) },
        'merchant identity lookup failed; falling back to synthetic label',
      );
    }

    const tail = apiKey.length >= 4 ? apiKey.slice(-4) : apiKey;
    return [toDiscoveredBrand(`cf-merchant-****${tail}`, `Commission Factory merchant (****${tail})`)];
  }

  // -------------------------------------------------------------------------
  // verifyAuth
  // -------------------------------------------------------------------------

  async verifyAuth(
    _ctx?: AdapterCallContext,
  ): Promise<{ ok: true; identity?: string } | { ok: false; reason: string }> {
    const r = await authVerify(this.now());
    if (r.ok) {
      return r.identity ? { ok: true, identity: r.identity } : { ok: true };
    }
    return { ok: false, reason: r.reason };
  }

  // -------------------------------------------------------------------------
  // listProgrammes — the merchant's own promotions.
  // -------------------------------------------------------------------------

  /**
   * Commission Factory's merchant surface exposes GET /Merchant/Promotions
   * rather than a distinct campaigns list; we map promotions to Programme.
   *   Source: https://dev.commissionfactory.com/V1/Merchant/Functions/GetPromotions/
   *   BLOCKED(verify): the Promotion payload field names against a live account.
   */
  async listProgrammes(query?: ProgrammeQuery, ctx?: AdapterCallContext): Promise<Programme[]> {
    requireCtx('listProgrammes', ctx);
    const apiKey = requireApiKey('listProgrammes');
    const env = await commissionFactoryAdvertiserRequest<
      CfMerchantPromotionArrayRaw | CfMerchantPromotionRaw[]
    >({
      operation: 'listProgrammes',
      path: '/Merchant/Promotions',
      apiKey,
      resilience: RESILIENCE.default,
    });
    let programmes = extractPromotions(env).map(toProgramme);
    if (query?.search) {
      const needle = query.search.toLowerCase();
      programmes = programmes.filter((p) => p.name.toLowerCase().includes(needle));
    }
    if (typeof query?.limit === 'number') programmes = programmes.slice(0, query.limit);
    return programmes;
  }

  // -------------------------------------------------------------------------
  // listTransactions — brand-scoped merchant transactions.
  // -------------------------------------------------------------------------

  async listTransactions(
    query?: TransactionQuery,
    ctx?: AdapterCallContext,
  ): Promise<Transaction[]> {
    requireCtx('listTransactions', ctx);
    const apiKey = requireApiKey('listTransactions');
    const now = this.now();

    // Commission Factory's GET /Merchant/Transactions requires fromDate/toDate.
    // Default to a 30-day window ending now when the caller does not supply one.
    const fromDate = (query?.from ?? defaultFrom(now)).slice(0, 10);
    const toDate = (query?.to ?? now.toISOString()).slice(0, 10);

    const env = await commissionFactoryAdvertiserRequest<
      CfMerchantTransactionArrayRaw | CfMerchantTransactionRaw[]
    >({
      operation: 'listTransactions',
      path: '/Merchant/Transactions',
      apiKey,
      query: { fromDate, toDate },
      resilience: RESILIENCE.listTransactions ?? RESILIENCE.default,
    });

    let txns = extractTransactions(env).map((r) => toTransaction(r, now));
    if (query?.programmeId) txns = txns.filter((t) => t.programmeId === query.programmeId);
    const statusFilter = toStatusList(query?.status);
    if (statusFilter && statusFilter.length > 0) {
      const set = new Set(statusFilter);
      txns = txns.filter((t) => set.has(t.status));
    }
    if (typeof query?.minAgeDays === 'number') {
      txns = txns.filter((t) => t.ageDays >= (query.minAgeDays as number));
    }
    if (typeof query?.maxAgeDays === 'number') {
      txns = txns.filter((t) => t.ageDays <= (query.maxAgeDays as number));
    }
    if (typeof query?.limit === 'number') txns = txns.slice(0, query.limit);
    return txns;
  }

  // -------------------------------------------------------------------------
  // getProgrammePerformance — per-publisher rollup (PRIMARY op).
  // -------------------------------------------------------------------------

  /**
   * Fetch merchant transactions for the window and roll them up per affiliate.
   * The merchant transactions surface supports an `affiliateId` filter, which
   * we use when the caller scopes to a single publisher.
   *   Source: https://dev.commissionfactory.com/V1/Merchant/Functions/GetTransactions/
   */
  async getProgrammePerformance(
    query?: ProgrammePerformanceQuery,
    ctx?: AdapterCallContext,
  ): Promise<ProgrammePerformanceRow[]> {
    requireCtx('getProgrammePerformance', ctx);
    const apiKey = requireApiKey('getProgrammePerformance');
    const now = this.now();

    const fromDate = (query?.from ?? defaultFrom(now)).slice(0, 10);
    const toDate = (query?.to ?? now.toISOString()).slice(0, 10);

    const env = await commissionFactoryAdvertiserRequest<
      CfMerchantTransactionArrayRaw | CfMerchantTransactionRaw[]
    >({
      operation: 'getProgrammePerformance',
      path: '/Merchant/Transactions',
      apiKey,
      query: { fromDate, toDate, affiliateId: query?.publisherId },
      resilience: RESILIENCE.getProgrammePerformance ?? RESILIENCE.default,
    });

    const txns = extractTransactions(env);
    let rows = rollupByAffiliate(txns, now);
    if (query?.publisherId) rows = rows.filter((r) => r.publisherId === query.publisherId);
    if (typeof query?.limit === 'number') rows = rows.slice(0, query.limit);
    return rows;
  }

  // -------------------------------------------------------------------------
  // Ops the advertiser side does NOT implement at v0.1.
  // -------------------------------------------------------------------------

  async getProgramme(_programmeId: string, _ctx?: AdapterCallContext): Promise<Programme> {
    throw new NotImplementedError(
      'Commission Factory advertiser adapter does not implement getProgramme at v0.1; use listProgrammes and filter client-side.',
    );
  }
  async getEarningsSummary(
    _query?: TransactionQuery,
    _ctx?: AdapterCallContext,
  ): Promise<EarningsSummary> {
    throw new NotImplementedError(
      'Commission Factory advertiser adapter does not implement getEarningsSummary at v0.1; use getProgrammePerformance for the per-publisher rollup.',
    );
  }
  async listClicks(_query?: ClickQuery, _ctx?: AdapterCallContext): Promise<Click[]> {
    throw new NotImplementedError(
      'Commission Factory does not expose click-level data on the merchant API; listClicks is unsupported.',
    );
  }
  async generateTrackingLink(
    _input: { programmeId: string; destinationUrl: string },
    _ctx?: AdapterCallContext,
  ): Promise<TrackingLink> {
    throw new NotImplementedError(
      'Commission Factory advertiser adapter does not generate tracking links — that is a publisher-side operation.',
    );
  }
  async listPublishers(): Promise<never> {
    throw new NotImplementedError(
      'Commission Factory advertiser adapter does not implement listPublishers at v0.1; per-publisher data is reported via getProgrammePerformance.',
    );
  }
  async listPublisherSectors(): Promise<never> {
    throw new NotImplementedError(
      'Not implemented for Commission Factory advertiser at v0.1.',
    );
  }

  // -------------------------------------------------------------------------
  // Setup + diagnostics
  // -------------------------------------------------------------------------

  async validateCredential(field: string, value: string): Promise<CredentialValidationResult> {
    return authValidate(field, value);
  }

  setupSteps(): SetupStep[] {
    return setupSteps();
  }

  async capabilitiesCheck(): Promise<NetworkCapabilities> {
    const operations: Record<string, OperationCapability> = {};
    operations['verifyAuth'] = {
      supported: true,
      note: 'Probes GET /Merchant/Transactions over a 1-day window; not re-probed here to avoid hitting the network during diagnostic.',
    };
    operations['listBrands'] = {
      supported: true,
      note:
        'Returns a single brand — a merchant key addresses one merchant. Identity derived from ' +
        'COMMISSION_FACTORY_ADVERTISER_MERCHANT_ID or a sample transaction. Built from docs, ' +
        'unverified against a live account.',
      claimStatus: 'experimental',
    };
    operations['listProgrammes'] = {
      supported: true,
      note: 'Maps GET /Merchant/Promotions to Programme. Promotion field names BLOCKED(verify) against a live account.',
      claimStatus: 'experimental',
    };
    operations['listTransactions'] = {
      supported: true,
      note: 'GET /Merchant/Transactions. Pagination not documented publicly; full window requested in one call.',
      claimStatus: 'experimental',
    };
    operations['getProgrammePerformance'] = {
      supported: true,
      note: 'Client-side per-publisher rollup of GET /Merchant/Transactions grouped by AffiliateId. Clicks not reported (0).',
      claimStatus: 'experimental',
    };
    operations['getProgramme'] = { supported: false, note: 'Not implemented at v0.1.' };
    operations['getEarningsSummary'] = { supported: false, note: 'Not implemented at v0.1.' };
    operations['listClicks'] = {
      supported: false,
      note: 'Click-level data not exposed on the Commission Factory merchant API.',
    };
    operations['generateTrackingLink'] = {
      supported: false,
      note: 'Publisher-side operation; not applicable to the advertiser adapter.',
    };
    return {
      network: SLUG,
      generatedAt: this.now().toISOString(),
      operations,
      knownLimitations: META.knownLimitations,
    };
  }
}

// ---------------------------------------------------------------------------
// Module-level registration
// ---------------------------------------------------------------------------

export const commissionFactoryAdvertiserAdapter = new CommissionFactoryAdvertiserAdapter();
registerAdapter(commissionFactoryAdvertiserAdapter);

// ---------------------------------------------------------------------------
// Local helpers
// ---------------------------------------------------------------------------

function defaultFrom(now: Date): string {
  return new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000).toISOString();
}

function toStatusList(
  v?: TransactionStatus | TransactionStatus[],
): TransactionStatus[] | undefined {
  if (v === undefined) return undefined;
  return Array.isArray(v) ? v : [v];
}

export const _internals = {
  toTransaction,
  toProgramme,
  toDiscoveredBrand,
  rollupByAffiliate,
  mapTransactionStatus,
  mapPerfStatus,
  mapPromotionStatus,
  computeAgeDays,
  nullableIso,
  toAmount,
  extractTransactions,
  extractPromotions,
  defaultFrom,
};
