/**
 * Commission Factory advertiser (merchant-side) auth + credential validation.
 *
 * Commission Factory authenticates with a single API key generated by the
 * account holder under their Account Settings. On the MERCHANT side the key is
 * issued under one merchant account and addresses only that merchant's data;
 * the key is passed as the `apiKey` QUERY PARAMETER on every request — there is
 * no OAuth flow and no bearer header.
 *   Source: https://dev.commissionfactory.com/V1/GeneratingApiKeys/
 *           https://dev.commissionfactory.com/V1/ (Getting Started)
 *
 * --- verifyAuth ----------------------------------------------------------------
 *
 * Commission Factory does not document a `/me`-style identity endpoint on the
 * merchant surface. We treat a successful, authorised call to
 * GET /Merchant/Transactions over a tiny date window as proof the key is valid
 * (a bad key returns 401/403). The API key is the account identity, so we
 * surface a redacted fingerprint of it rather than the raw key.
 *
 * verifyAuth never throws — it is called by error handlers, and a 401/403 must
 * resolve to { ok: false } rather than bubble up.
 *
 * Read-only optional account hint:
 *   COMMISSION_FACTORY_ADVERTISER_MERCHANT_ID is OPTIONAL. The merchant key
 *   already scopes data to one merchant, so the id is not needed to address the
 *   API. When set it is used purely as a stable `networkBrandId` / display
 *   label for `listBrands` and the brand resolver; otherwise the adapter
 *   derives the merchant identity from a sample transaction (MerchantId /
 *   MerchantName) at discovery time.
 */

import { commissionFactoryAdvertiserRequest } from './client.js';
import { requireCredential } from '../../shared/config.js';
import { buildErrorEnvelope, NetworkError } from '../../shared/errors.js';
import { DEFAULT_RESILIENCE } from '../../shared/resilience.js';
import type { CredentialValidationResult, NetworkErrorEnvelope } from '../../shared/types.js';
import { createLogger } from '../../shared/logging.js';

const log = createLogger('commission-factory-advertiser.auth');

export const SLUG = 'commission-factory-advertiser';

export const API_KEY_FIELD = 'COMMISSION_FACTORY_ADVERTISER_API_KEY';
export const MERCHANT_ID_FIELD = 'COMMISSION_FACTORY_ADVERTISER_MERCHANT_ID';

/**
 * Read the configured API key, or throw a `config_error` envelope via
 * `requireCredential` if it is missing.
 */
export function requireApiKey(operation: string): string {
  return requireCredential(API_KEY_FIELD, {
    network: SLUG,
    operation,
    hint:
      `Set ${API_KEY_FIELD} in ~/.affiliate-mcp/.env. ` +
      'Generate it in the Commission Factory dashboard under your merchant Account Settings → API. ' +
      'The merchant key is read by this adapter for reporting only; it never issues writes.',
  });
}

/**
 * Read the OPTIONAL merchant id hint. Returns undefined when unset — the
 * merchant key already scopes data to one merchant, so this is not required.
 */
export function optionalMerchantId(): string | undefined {
  const v = process.env[MERCHANT_ID_FIELD];
  if (v === undefined) return undefined;
  const trimmed = v.trim();
  return trimmed === '' ? undefined : trimmed;
}

/**
 * Produce a short, non-reversible fingerprint of the API key for display in the
 * setup wizard. We never echo the raw key back to the user.
 */
function fingerprint(apiKey: string): string {
  const tail = apiKey.length >= 4 ? apiKey.slice(-4) : apiKey;
  return `commission-factory-advertiser/key:****${tail}`;
}

export interface VerifyAuthOk {
  ok: true;
  identity?: string;
}

export interface VerifyAuthFail {
  ok: false;
  reason: string;
  envelope?: NetworkErrorEnvelope;
}

/**
 * A small recent date window for the auth probe. Commission Factory's
 * GET /Merchant/Transactions requires fromDate/toDate; we ask for a 1-day
 * window ending now so the payload stays small. The status of the result does
 * not matter — only that the key is accepted (non-401/403).
 */
function probeWindow(now: Date): { fromDate: string; toDate: string } {
  const to = now;
  const from = new Date(now.getTime() - 24 * 60 * 60 * 1000);
  const iso = (d: Date): string => d.toISOString().slice(0, 10);
  return { fromDate: iso(from), toDate: iso(to) };
}

/**
 * Verify Commission Factory merchant credentials by making a cheap authorised
 * call to GET /Merchant/Transactions over a 1-day window.
 *
 * Never throws — returns { ok: false } on any failure.
 */
export async function verifyAuth(now: Date = new Date()): Promise<VerifyAuthOk | VerifyAuthFail> {
  let apiKey: string;
  try {
    apiKey = requireApiKey('verifyAuth');
  } catch (err) {
    if (err instanceof NetworkError) {
      return { ok: false, reason: err.envelope.message, envelope: err.envelope };
    }
    throw err;
  }

  try {
    const { fromDate, toDate } = probeWindow(now);
    await commissionFactoryAdvertiserRequest<unknown>({
      operation: 'verifyAuth',
      path: '/Merchant/Transactions',
      apiKey,
      query: { fromDate, toDate },
      resilience: DEFAULT_RESILIENCE,
    });

    const identity = fingerprint(apiKey);
    log.debug({ identity }, 'commission-factory-advertiser verifyAuth succeeded');
    return { ok: true, identity };
  } catch (err) {
    if (err instanceof NetworkError) {
      return { ok: false, reason: err.envelope.message, envelope: err.envelope };
    }
    const envelope = buildErrorEnvelope({
      type: 'auth_error',
      network: SLUG,
      operation: 'verifyAuth',
      message: err instanceof Error ? err.message : String(err),
      hint: `Check ${API_KEY_FIELD} in your config.`,
    });
    return { ok: false, reason: envelope.message, envelope };
  }
}

/**
 * Validate a single credential field at wizard-entry time.
 *
 * COMMISSION_FACTORY_ADVERTISER_API_KEY: format check (non-empty) followed by a
 *   live probe against GET /Merchant/Transactions with the entered value.
 * COMMISSION_FACTORY_ADVERTISER_MERCHANT_ID: optional; format check only.
 */
export async function validateCredential(
  field: string,
  value: string,
): Promise<CredentialValidationResult> {
  if (field === MERCHANT_ID_FIELD) {
    // Optional hint. Empty is acceptable. When present it should look like an id.
    if (!value || value.trim() === '') {
      return {
        ok: true,
        message:
          'Optional. Left blank — the merchant key already scopes data to one merchant; the ' +
          'adapter will derive the merchant identity from a sample transaction.',
      };
    }
    if (!/^[A-Za-z0-9_-]+$/.test(value.trim())) {
      return {
        ok: false,
        message: 'Merchant id looks malformed (expected an alphanumeric identifier).',
        hint: 'Copy the merchant/account id exactly, or leave this blank to auto-derive it.',
      };
    }
    return { ok: true };
  }

  if (field !== API_KEY_FIELD) {
    return {
      ok: false,
      message: `Unknown credential field "${field}" for Commission Factory advertiser.`,
      hint: `Commission Factory advertiser expects ${API_KEY_FIELD} (and optional ${MERCHANT_ID_FIELD}).`,
    };
  }

  if (!value || value.trim() === '') {
    return {
      ok: false,
      message: 'API key must not be empty.',
      hint: 'Generate it in the Commission Factory dashboard under your merchant Account Settings → API.',
    };
  }

  // Temporarily inject the entered value so we can exercise the live probe.
  const prev = process.env[API_KEY_FIELD];
  process.env[API_KEY_FIELD] = value;
  try {
    const result = await verifyAuth();
    if (result.ok) {
      return {
        ok: true,
        message: result.identity ?? 'Credentials verified against the Commission Factory merchant API.',
      };
    }
    return {
      ok: false,
      message: result.reason,
      hint: 'Check the API key was copied without leading or trailing spaces, and that it has not been revoked.',
    };
  } finally {
    if (prev === undefined) {
      delete process.env[API_KEY_FIELD];
    } else {
      process.env[API_KEY_FIELD] = prev;
    }
  }
}
