/**
 * Commission Factory advertiser (merchant-side) HTTP client.
 *
 * READ-ONLY by design: the client refuses any non-GET method at runtime so the
 * adapter cannot accidentally ship a write operation. The Commission Factory
 * merchant surface does expose mutation endpoints elsewhere; this adapter ships
 * read-only at v0.1 and a future contributor must consciously lift the guard.
 * This is the ONLY path adapter methods use for network I/O.
 *
 * --- Commission Factory API surface (from public docs, 2026-06-04) ------------
 *
 * Base URL: https://api.commissionfactory.com/V1/
 *   Source: https://dev.commissionfactory.com/V1/ (Getting Started)
 *
 * Authentication: a single API key, generated by the account holder under their
 * merchant Account Settings. The key is passed as the `apiKey` QUERY PARAMETER
 * on every request (NOT an Authorization/bearer header). Example from the docs:
 *   GET https://api.commissionfactory.com/V1/Merchant/Transactions?apiKey=[apiKey]
 *   Source: https://dev.commissionfactory.com/V1/GeneratingApiKeys/
 *
 * Merchant (advertiser-side) endpoints used:
 *   GET /V1/Merchant/Transactions  → ?fromDate=&toDate=&dateProperty=&affiliateId=&status=&status2=
 *   GET /V1/Merchant/Promotions    → ?affiliateId=&affiliateContactName=&affiliateBusinessName=
 *   Source: https://dev.commissionfactory.com/V1/Merchant/Functions/
 *           https://dev.commissionfactory.com/V1/Merchant/Functions/GetTransactions/
 *           https://dev.commissionfactory.com/V1/Merchant/Functions/GetPromotions/
 *
 * Content negotiation: JSON by default; the adapter sends `Accept: application/json`.
 *   Source: https://dev.commissionfactory.com/V1/JsonOrXml/
 *
 * Hard rules:
 *   1. Do NOT call `fetch` from adapter.ts or anywhere else in this folder.
 *   2. Do NOT bypass `withResilience` for any call.
 *   3. On non-2xx, throw `HttpStatusError` so the resilience layer retries uniformly.
 *   4. Preserve the raw response body verbatim on failure (`networkErrorBody`).
 *   5. Refuse any non-GET method client-side.
 */

import {
  HttpStatusError,
  withResilience,
  type WithResilienceContext,
} from '../../shared/resilience.js';
import { buildErrorEnvelope, NetworkError } from '../../shared/errors.js';
import type { ResilienceConfig } from '../../shared/types.js';
import { createLogger } from '../../shared/logging.js';

const log = createLogger('commission-factory-advertiser.client');

const SLUG = 'commission-factory-advertiser';

/**
 * The Commission Factory production API base URL.
 * Source: https://dev.commissionfactory.com/V1/
 */
export const COMMISSION_FACTORY_ADV_BASE_URL = 'https://api.commissionfactory.com/V1/';

export interface CommissionFactoryAdvRequestInput {
  /** The canonical operation name. Used as the breaker key and in error envelopes. */
  operation: string;
  /** Path beginning with `/` — joined to the base URL (relative to /V1/). */
  path: string;
  /** The API key, injected as the `apiKey` query parameter. */
  apiKey: string;
  /** Method. Always `GET` at v0.1; passing anything else throws a config_error. */
  method?: 'GET';
  /** Query string parameters. Values with `undefined` are skipped. */
  query?: Record<string, string | number | undefined>;
  /** Resilience knobs for this specific call. */
  resilience: ResilienceConfig;
  /** Override base URL (kept for parity with other adapters; rarely needed). */
  baseUrl?: string;
  /** Optional AbortSignal for cooperative cancellation in tests. */
  signal?: AbortSignal;
}

/**
 * Issue a single Commission Factory merchant API request under the resilience
 * policy.
 *
 * Cardinal: only GET is permitted. Any other method throws a `config_error`
 * before the network call goes out.
 */
export async function commissionFactoryAdvertiserRequest<T>(
  input: CommissionFactoryAdvRequestInput,
): Promise<T> {
  // Hard read-only guard. This adapter ships read-only at v0.1 and a future
  // contributor must consciously remove this throw to enable writes.
  const method = input.method ?? 'GET';
  if (method !== 'GET') {
    throw new NetworkError(
      buildErrorEnvelope({
        type: 'config_error',
        network: SLUG,
        operation: input.operation,
        message: `Commission Factory advertiser adapter is read-only at v0.1; refusing ${method}.`,
        hint:
          'This adapter only issues GET requests. To enable writes a future PR must lift this ' +
          'guard explicitly.',
      }),
    );
  }

  const ctx: WithResilienceContext = { network: SLUG, operation: input.operation };
  const base = input.baseUrl ?? COMMISSION_FACTORY_ADV_BASE_URL;

  return withResilience(
    ctx,
    async () => {
      // The API key is a query parameter, not a header (verified from the docs).
      const query = { ...(input.query ?? {}), apiKey: input.apiKey };
      const url = buildUrl(base, input.path, query);
      const init: RequestInit = {
        method: 'GET',
        headers: { Accept: 'application/json' },
      };
      if (input.signal) {
        init.signal = input.signal;
      }

      // Never log the URL with the key in it — log only the path + operation.
      log.debug(
        { path: input.path, method: init.method, operation: input.operation },
        'commission-factory-advertiser request',
      );

      const res = await fetch(url, init);
      const rawBody = await res.text();

      if (!res.ok) {
        throw new HttpStatusError(
          res.status,
          rawBody,
          `Commission Factory advertiser ${input.operation} GET ${input.path} → HTTP ${res.status}`,
        );
      }

      const trimmed = rawBody.trim();
      if (trimmed === '' || trimmed === 'null') {
        return {} as T;
      }

      try {
        return JSON.parse(rawBody) as T;
      } catch (err) {
        throw new NetworkError(
          buildErrorEnvelope({
            type: 'network_api_error',
            network: SLUG,
            operation: input.operation,
            httpStatus: res.status,
            networkErrorBody: rawBody,
            message: `Commission Factory advertiser ${input.operation} returned HTTP ${res.status} with non-JSON body (parse error: ${(err as Error).message})`,
          }),
        );
      }
    },
    input.resilience,
  );
}

/**
 * Compose the absolute URL for a merchant-relative path under /V1/.
 * Exported so tests can assert URL shape directly.
 */
export function buildUrl(
  base: string,
  pathname: string,
  query?: Record<string, string | number | undefined>,
): string {
  // The base URL carries the /V1/ segment; join relative paths against it.
  // A path like `/Merchant/Transactions` resolves to
  // `https://api.commissionfactory.com/V1/Merchant/Transactions`.
  const relative = pathname.startsWith('/') ? pathname.slice(1) : pathname;
  const baseWithSlash = base.endsWith('/') ? base : `${base}/`;
  const url = new URL(relative, baseWithSlash);
  if (query) {
    for (const [k, v] of Object.entries(query)) {
      if (v === undefined) continue;
      url.searchParams.set(k, String(v));
    }
  }
  return url.toString();
}

export { HttpStatusError };
