/**
 * Adrecord auth + credential validation.
 *
 * Adrecord (a Nordic / Swedish network) authenticates with a single private
 * API key. The key is generated by the affiliate from the publisher dashboard
 * (Settings → API) and is long-lived; there is no refresh flow. It is delivered
 * via a custom `APIKEY` request header (Adrecord also accepts it as a GET/POST
 * variable, but a header keeps the secret out of URLs and logs — see
 * `client.ts`).
 *
 * Because the key is already scoped to a single publisher account, there is no
 * second identifier (account / publisher id) to derive: the publisher-side
 * adapter is single-brand and reads one credential, `ADRECORD_API_KEY`. We
 * therefore do not implement the Awin `derivedValues` pattern.
 *
 * --- Auth check -------------------------------------------------------------
 *
 * `verifyAuth()` calls `GET /programs?limit=1`, the cheapest authenticated
 * affiliate endpoint. A valid key returns 200 with a JSON payload; an invalid
 * key returns a non-2xx status which the client turns into an `HttpStatusError`
 * and the resilience layer classifies (a 401/403 becomes an `auth_error`
 * envelope). We never throw from `verifyAuth` — it is called by error handlers,
 * so a throw here would loop.
 */

import { adrecordRequest } from './client.js';
import { requireCredential } from '../../shared/config.js';
import { buildErrorEnvelope, NetworkError } from '../../shared/errors.js';
import { DEFAULT_RESILIENCE } from '../../shared/resilience.js';
import type { CredentialValidationResult, NetworkErrorEnvelope } from '../../shared/types.js';
import { createLogger } from '../../shared/logging.js';

const log = createLogger('adrecord.auth');

export const ADRECORD_SLUG = 'adrecord';
export const ADRECORD_API_KEY_FIELD = 'ADRECORD_API_KEY';

export interface VerifyAuthOk {
  ok: true;
  identity?: string;
}

export interface VerifyAuthFail {
  ok: false;
  reason: string;
  envelope?: NetworkErrorEnvelope;
}

/**
 * Read the Adrecord API key. Throws a `config_error` NetworkError when missing
 * so callers surface an actionable envelope rather than a bare undefined.
 */
export function requireApiKey(operation: string): string {
  return requireCredential(ADRECORD_API_KEY_FIELD, {
    network: ADRECORD_SLUG,
    operation,
    hint: 'Generate a private API key in the Adrecord publisher dashboard under Settings → API.',
  });
}

/**
 * Verify the Adrecord API key by calling `GET /programs?limit=1`.
 *
 * Why this endpoint: it is the smallest authenticated affiliate call (one
 * programme row), it confirms the key is live, and it does not mutate anything.
 * The API key is already scoped to a single publisher account so there is no
 * identifier to derive — the identity string is a fixed "authenticated" marker.
 */
export async function verifyAuth(): Promise<VerifyAuthOk | VerifyAuthFail> {
  let apiKey: string;
  try {
    apiKey = requireApiKey('verifyAuth');
  } catch (err) {
    if (err instanceof NetworkError) {
      return { ok: false, reason: err.envelope.message, envelope: err.envelope };
    }
    throw err;
  }

  try {
    await adrecordRequest<unknown>({
      operation: 'verifyAuth',
      path: '/programs',
      apiKey,
      query: { limit: 1 },
      resilience: DEFAULT_RESILIENCE,
    });

    log.debug('adrecord verifyAuth succeeded');
    return { ok: true, identity: 'adrecord (authenticated)' };
  } catch (err) {
    if (err instanceof NetworkError) {
      return { ok: false, reason: err.envelope.message, envelope: err.envelope };
    }
    const envelope = buildErrorEnvelope({
      type: 'network_api_error',
      network: ADRECORD_SLUG,
      operation: 'verifyAuth',
      message: err instanceof Error ? err.message : String(err),
    });
    return { ok: false, reason: envelope.message, envelope };
  }
}

/**
 * Validate a single credential field at wizard-entry time.
 *
 * ADRECORD_API_KEY:
 *   Writes the candidate key into `process.env`, calls `verifyAuth()`, then
 *   restores the previous value (test isolation; a failed validation must not
 *   poison subsequent operations in the same process). Returns `ok` on success.
 */
export async function validateCredential(
  field: string,
  value: string,
): Promise<CredentialValidationResult> {
  if (field === ADRECORD_API_KEY_FIELD) {
    const previous = process.env[ADRECORD_API_KEY_FIELD];
    process.env[ADRECORD_API_KEY_FIELD] = value;
    try {
      const result = await verifyAuth();
      if (result.ok) {
        return { ok: true, message: result.identity ?? 'API key verified' };
      }
      return {
        ok: false,
        message: result.reason,
        hint:
          'Check the key in the Adrecord publisher dashboard under Settings → API. The key may be ' +
          'revoked, regenerated, or copied with leading/trailing whitespace.',
      };
    } finally {
      if (previous === undefined) {
        delete process.env[ADRECORD_API_KEY_FIELD];
      } else {
        process.env[ADRECORD_API_KEY_FIELD] = previous;
      }
    }
  }

  return {
    ok: false,
    message: `Unknown credential field "${field}" for Adrecord.`,
    hint: 'Adrecord expects ADRECORD_API_KEY (required).',
  };
}
